/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// Páginas regionais de Vidraçaria. Copy ~80% única por cidade, reutilizando a estrutura
// de seções da página de Vidraçaria (CategoryPillar) via a prop `region`.

import { RegionPage } from './regionsEsquadrias';

const IMG = {
  esq: '/assets/images/esquadrias_aluminio_luxury_card_1782739998198.jpg',
  villa: '/assets/images/luxury_villa_glazing_1782306007983.jpg',
  min: '/assets/images/minimal_aluminum_frames_1782306022668.jpg',
  facade: '/assets/images/modern_facade_glass_1782306036555.jpg',
  house: '/assets/images/portfolio_house_luxury_card_1782740031450.jpg',
  vidro: '/assets/images/vidracaria_balcony_luxury_card_1782740008784.jpg',
  serr: '/assets/images/serralheria_staircase_luxury_card_1782740019768.jpg',
};

export const VIDRACARIA_SP_SLUG = 'vidracaria-em-sao-paulo-sp';

export const VIDRACARIA_REGIONS: RegionPage[] = [
  {
    slug: 'vidracaria-em-alphaville-sp',
    city: 'Alphaville',
    keyword: 'Vidraçaria em Alphaville SP',
    metaTitle: 'Vidraçaria em Alphaville SP | Guarda-Corpo de Vidro e Box | Serra Ferro',
    metaDescription: 'Vidraçaria de alto padrão em Alphaville SP: guarda-corpo de vidro, pele de vidro, box e espelhos sob medida com fixação invisível. Fábrica na região. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • VIDRAÇARIA EM ALPHAVILLE SP',
      description: 'Vidraçaria de alto padrão em Alphaville com fábrica na região: guarda-corpos autoportantes, pele de vidro, espelhos monumentais e box sob medida, com fixação invisível e transparência total.',
      highlights: ['Fábrica na região de Alphaville', 'Guarda-corpo com fixação invisível', 'Pele de vidro e espelhos', 'Vidros laminados de segurança'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM ALPHAVILLE',
      title: 'Vidraçaria de Alto Padrão em Alphaville',
      paragraphs: [
        'As residências contemporâneas de Alphaville pedem vidro em grande escala: guarda-corpos autoportantes que preservam a vista, peles de vidro, coberturas e espelhos monumentais. Com a fábrica na própria região, instalamos com fixação invisível por canalete embutido e vidros laminados de máxima segurança.',
        'Trabalhamos junto aos arquitetos dos condomínios, dimensionando as espessuras conforme a NBR 14718 e cuidando do içamento de vidros de grande formato com equipamento a vácuo e equipe certificada.',
      ],
      bullets: ['Sede em Alphaville Industrial, Barueri', 'Guarda-corpo autoportante clean', 'Pele de vidro e coberturas', 'Içamento de vidros jumbo'],
    },
    headers: {
      servicesTitle: 'Vidraçaria em Alphaville SP: Serviços de Alto Padrão',
      servicesSubtitle: 'Guarda-corpos de vidro, pele de vidro, espelhos e box sob medida para as residências de altíssimo padrão de Alphaville, com fixação invisível.',
      linesTitle: 'Tipos de Vidro Premium para Obras em Alphaville',
      linesSubtitle: 'Do extra clear ao laminado de segurança e ao controle solar, escolha a tecnologia de vidro ideal para a sua obra em Alphaville.',
      casesTitle: 'Projetos de Vidraçaria Entregues em Alphaville',
      casesSubtitle: 'Guarda-corpos, peles de vidro e espelhos executados nos condomínios de Alphaville com transparência e segurança.',
      testimonialsTitle: 'Quem Contratou Vidraçaria em Alphaville Recomenda',
      testimonialsSubtitle: 'Moradores e arquitetos de Alphaville comentam a transparência e a segurança dos vidros.',
      faqTitle: 'Dúvidas sobre Vidraçaria em Alphaville',
      faqSubtitle: 'Respostas técnicas sobre guarda-corpos, espelhos e pele de vidro em Alphaville.',
      contactTitle: 'Peça um Orçamento de Vidraçaria em Alphaville SP',
      contactSubtitle: 'Estamos na região de Alphaville. Fale com o comercial técnico no WhatsApp e agende a medição.',
    },
    cases: [
      { title: 'Guarda-Corpo Autoportante - Residencial Alphaville', region: 'Alphaville', description: 'Guarda-corpo de vidro laminado temperado com canalete embutido, sem colunas, preservando a vista da área de lazer.', image: IMG.vidro, highlight: 'Fixação Invisível' },
      { title: 'Pele de Vidro - Mansão em Alphaville', region: 'Alphaville', description: 'Fachada em pele de vidro com controle solar e canto de vidro sem coluna, maximizando luz e transparência.', image: IMG.facade, highlight: 'Pele de Vidro' },
      { title: 'Espelho Monumental - Alphaville', region: 'Alphaville', description: 'Espelho de cristal de alta definição com corte bisotê e iluminação integrada para hall e sala de jantar.', image: IMG.house, highlight: 'Espelho de Cristal' },
    ],
    testimonials: [
      { author: 'Henrique Salles', role: 'Morador de Alphaville', text: 'O guarda-corpo de vidro ficou totalmente clean, sem colunas atrapalhando a vista. Sinto total segurança com a espessura do vidro.' },
      { author: 'Arq. Camila Prado', role: 'Arquiteta em Alphaville', text: 'Dimensionaram os vidros pela norma e fizeram o içamento dos painéis grandes com maestria. Acabamento impecável.' },
    ],
    faqs: [
      { question: 'O guarda-corpo de vidro é seguro em Alphaville?', answer: 'Sim. Usamos vidro laminado temperado que, em caso de quebra, mantém os fragmentos presos à película, e dimensionamos tudo pela NBR 14718 — padrão exigido nas residências de alto padrão de Alphaville.' },
      { question: 'Vocês fazem pele de vidro e coberturas de vidro?', answer: 'Sim, executamos peles de vidro (structural glazing), cantos de vidro sem coluna e coberturas com vidro laminado de controle solar, com vedação total contra chuva.' },
      { question: 'A fábrica fica perto de Alphaville?', answer: 'Sim, nossa sede fica em Alphaville Industrial, Barueri, garantindo agilidade de medição, fabricação e instalação.' },
      { question: 'Como é feito o içamento de vidros grandes?', answer: 'Com ventosas pneumáticas a vácuo, cabos de alta resistência e equipe certificada em trabalho em altura, garantindo segurança total no içamento de painéis jumbo.' },
    ],
  },
  {
    slug: 'vidracaria-em-cajamar-sp',
    city: 'Cajamar',
    keyword: 'Vidraçaria em Cajamar SP',
    metaTitle: 'Vidraçaria em Cajamar SP | Guarda-Corpo de Vidro e Sacadas | Serra Ferro',
    metaDescription: 'Vidraçaria em Cajamar SP: guarda-corpo de vidro, fechamento de sacada e coberturas de vidro calculados para vento, com vidros laminados de segurança. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • VIDRAÇARIA EM CAJAMAR SP',
      description: 'Vidraçaria em Cajamar para condomínios em relevo: guarda-corpos de vidro, fechamentos de sacada e coberturas dimensionados para o vento das áreas altas, com vidros laminados de segurança.',
      highlights: ['Vidros calculados para vento', 'Guarda-corpo pela NBR 14718', 'Fechamento de sacada e coberturas', 'Vedação total contra chuva'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM CAJAMAR',
      title: 'Vidraçaria em Cajamar para Condomínios em Relevo',
      paragraphs: [
        'Os condomínios de alto padrão de Cajamar, como a Reserva Santa Maria, ficam em áreas elevadas onde os guarda-corpos de vidro e os fechamentos de sacada precisam suportar cargas de vento maiores. Dimensionamos as espessuras e as fixações pela NBR 14718 para segurança total, sem abrir mão da transparência.',
        'Atendemos Cajamar, Polvilho e Jordanésia com fechamentos de sacada retráteis, coberturas de vidro com vedação reforçada e guarda-corpos autoportantes voltados à paisagem.',
      ],
      bullets: ['Cálculo de vento (NBR 14718)', 'Cobertura em Polvilho e Jordanésia', 'Fechamento de sacada retrátil', 'Coberturas de vidro com vedação'],
    },
    headers: {
      servicesTitle: 'Vidraçaria em Cajamar SP: Guarda-Corpos e Sacadas',
      servicesSubtitle: 'Guarda-corpos de vidro, fechamentos de sacada e coberturas sob medida para condomínios de Cajamar, dimensionados para o vento das áreas de relevo.',
      linesTitle: 'Tipos de Vidro Premium para Obras em Cajamar',
      linesSubtitle: 'Do laminado de segurança ao controle solar, escolha a tecnologia de vidro ideal para a exposição da sua obra em Cajamar.',
      casesTitle: 'Projetos de Vidraçaria Entregues em Cajamar',
      casesSubtitle: 'Guarda-corpos e fechamentos executados em condomínios de Cajamar com segurança contra o vento.',
      testimonialsTitle: 'Quem Contratou Vidraçaria em Cajamar Recomenda',
      testimonialsSubtitle: 'Moradores dos condomínios de Cajamar comentam a segurança e a vedação dos vidros.',
      faqTitle: 'Dúvidas sobre Vidraçaria em Cajamar',
      faqSubtitle: 'Respostas técnicas sobre guarda-corpos, sacadas e coberturas de vidro em Cajamar.',
      contactTitle: 'Peça um Orçamento de Vidraçaria em Cajamar SP',
      contactSubtitle: 'Agende a visita técnica da sua casa em Cajamar e fale com o nosso comercial pelo WhatsApp.',
    },
    cases: [
      { title: 'Guarda-Corpo Autoportante - Reserva Santa Maria (Cajamar)', region: 'Reserva Santa Maria - Cajamar', description: 'Guarda-corpo de vidro laminado temperado dimensionado para o vento da área elevada, voltado à paisagem, sem colunas.', image: IMG.vidro, highlight: 'Reforço de Vento' },
      { title: 'Fechamento de Sacada - Polvilho (Cajamar)', region: 'Polvilho - Cajamar', description: 'Fechamento de sacada retrátil com vedação de alta densidade contra a chuva com vento das áreas altas.', image: IMG.villa, highlight: 'Sacada Retrátil' },
      { title: 'Cobertura de Vidro - Jordanésia (Cajamar)', region: 'Jordanésia - Cajamar', description: 'Cobertura em vidro laminado de controle solar com calhas integradas e vedação dupla contra infiltração.', image: IMG.facade, highlight: 'Cobertura de Vidro' },
    ],
    testimonials: [
      { author: 'Vinícius Barros', role: 'Morador da Reserva Santa Maria, Cajamar', text: 'A casa fica no alto e o vento é forte. O guarda-corpo de vidro é firme, seguro e não tira nada da vista da serra.' },
      { author: 'Arq. Renata Coelho', role: 'Arquiteta em Cajamar', text: 'Dimensionaram os vidros pela norma considerando o vento da região. Fechamento de sacada impecável e sem vazamento.' },
    ],
    faqs: [
      { question: 'O guarda-corpo de vidro aguenta o vento das áreas altas de Cajamar?', answer: 'Sim. Calculamos a espessura do vidro e as fixações pela NBR 14718 considerando as cargas de vento do relevo de Cajamar, garantindo segurança total.' },
      { question: 'O fechamento de sacada veda bem contra chuva com vento?', answer: 'Sim. Usamos vedação de alta densidade, escovas hidrófugas e canais de drenagem, essenciais para as sacadas expostas dos condomínios elevados de Cajamar.' },
      { question: 'Vocês atendem a Reserva Santa Maria e outros condomínios de Cajamar?', answer: 'Sim, atendemos os condomínios de alto padrão de Cajamar, Polvilho e Jordanésia, com medição no local e respeito às regras de acesso.' },
      { question: 'Fazem coberturas de vidro em Cajamar?', answer: 'Sim, executamos coberturas em vidro laminado de controle solar, com calhas integradas e vedação dupla contra infiltrações.' },
    ],
  },
  {
    slug: 'vidracaria-em-itapevi-sp',
    city: 'Itapevi',
    keyword: 'Vidraçaria em Itapevi SP',
    metaTitle: 'Vidraçaria em Itapevi SP | Box, Guarda-Corpo e Espelhos | Serra Ferro',
    metaDescription: 'Vidraçaria em Itapevi SP para obras novas e condomínios: box de banheiro, guarda-corpo de vidro, espelhos e fechamentos sob medida com fixação invisível. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • VIDRAÇARIA EM ITAPEVI SP',
      description: 'Vidraçaria em Itapevi para obras novas e condomínios: box de banheiro premium, guarda-corpos de vidro, espelhos e fechamentos de sacada sob medida, com fixação invisível e prazo em contrato.',
      highlights: ['Ideal para obra nova', 'Box premium e espelhos', 'Guarda-corpo de vidro seguro', 'Fixação invisível'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM ITAPEVI',
      title: 'Vidraçaria em Itapevi para Obra Nova e Condomínios',
      paragraphs: [
        'Itapevi cresce com novos condomínios e casas em Cohab, Jardim Briquet e Vila Nova Itapevi, e o vidro dá o acabamento final: box de banheiro, guarda-corpos de escada e sacada, espelhos e divisórias. Medimos com precisão os vãos da obra nova para uma instalação perfeita.',
        'Trabalhamos com vidros temperados e laminados de segurança, roldanas de inox nos boxes e fixações invisíveis nos guarda-corpos, com prazo definido em contrato.',
      ],
      bullets: ['Box de banheiro com inox', 'Guarda-corpos de escada e sacada', 'Espelhos e divisórias de vidro', 'Cobertura na Cohab e Jardim Briquet'],
    },
    headers: {
      servicesTitle: 'Vidraçaria em Itapevi SP: Serviços Sob Medida',
      servicesSubtitle: 'Box, guarda-corpos de vidro, espelhos e fechamentos sob medida para obras novas e condomínios de Itapevi, com fixação invisível.',
      linesTitle: 'Tipos de Vidro Premium para Obras em Itapevi',
      linesSubtitle: 'Do temperado ao laminado de segurança, escolha a tecnologia de vidro ideal para a sua obra em Itapevi.',
      casesTitle: 'Projetos de Vidraçaria Entregues em Itapevi',
      casesSubtitle: 'Boxes, guarda-corpos e espelhos executados em obras novas e condomínios de Itapevi.',
      testimonialsTitle: 'Quem Contratou Vidraçaria em Itapevi Recomenda',
      testimonialsSubtitle: 'Moradores e construtores de Itapevi comentam o acabamento e a pontualidade.',
      faqTitle: 'Dúvidas sobre Vidraçaria em Itapevi',
      faqSubtitle: 'Respostas para box, guarda-corpos e espelhos em obras de Itapevi.',
      contactTitle: 'Peça um Orçamento de Vidraçaria em Itapevi SP',
      contactSubtitle: 'Agende a medição da sua obra em Itapevi e fale com o comercial técnico pelo WhatsApp.',
    },
    cases: [
      { title: 'Box e Espelhos - Casa Nova em Jardim Briquet (Itapevi)', region: 'Jardim Briquet - Itapevi', description: 'Box de banheiro premium com roldanas de inox e espelhos lapidados, instalados na obra nova com esquadro perfeito.', image: IMG.vidro, highlight: 'Box Premium' },
      { title: 'Guarda-Corpo de Escada - Cohab (Itapevi)', region: 'Cohab - Itapevi', description: 'Guarda-corpo de vidro laminado para escada interna, com fixação por botões de inox e transparência total.', image: IMG.house, highlight: 'Guarda-Corpo' },
      { title: 'Fechamento de Sacada - Vila Nova (Itapevi)', region: 'Vila Nova - Itapevi', description: 'Fechamento de sacada em vidro temperado com roldanas ocultas e vedação contra chuva, em condomínio novo.', image: IMG.villa, highlight: 'Sacada' },
    ],
    testimonials: [
      { author: 'Anderson Melo', role: 'Proprietário de casa nova em Itapevi', text: 'Chamei ainda na obra e o box e os espelhos ficaram perfeitos, sem gambiarra. Instalação no prazo combinado.' },
      { author: 'Eng. Priscila Santos', role: 'Construtora em Itapevi', text: 'Guarda-corpos e fechamentos entregues com documentação e esquadro certinho. Ótimo parceiro para as obras que tocamos em Itapevi.' },
    ],
    faqs: [
      { question: 'Vale contratar a vidraçaria ainda na obra em Itapevi?', answer: 'Sim. Medindo na fase certa, garantimos que box, guarda-corpos e espelhos fiquem com esquadro perfeito e instalação limpa, sem retrabalho.' },
      { question: 'O box tem roldanas de qualidade?', answer: 'Sim, usamos roldanas de inox de alta durabilidade e vidros temperados de segurança, com acabamento premium.' },
      { question: 'O guarda-corpo de vidro é seguro?', answer: 'Sim, usamos vidro laminado e seguimos a NBR 14718, garantindo segurança em escadas e sacadas.' },
      { question: 'Fazem espelhos e divisórias em Itapevi?', answer: 'Sim, fabricamos espelhos lapidados sob medida e divisórias de vidro temperado para os ambientes da sua obra.' },
    ],
  },
  {
    slug: 'vidracaria-em-barueri-sp',
    city: 'Barueri',
    keyword: 'Vidraçaria em Barueri SP',
    metaTitle: 'Vidraçaria em Barueri SP | Guarda-Corpo de Vidro e Box | Serra Ferro',
    metaDescription: 'Vidraçaria em Barueri SP com fábrica em Alphaville: guarda-corpo de vidro, pele de vidro, box e espelhos sob medida com fixação invisível e vidros de segurança. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • VIDRAÇARIA EM BARUERI SP',
      description: 'Somos vidraçaria com fábrica em Barueri, sediada em Alphaville Industrial: guarda-corpos autoportantes, pele de vidro, box e espelhos sob medida, com fixação invisível e agilidade de fábrica local.',
      highlights: ['Fábrica própria em Barueri', 'Residencial e corporativo', 'Guarda-corpo com fixação invisível', 'Vidros laminados de segurança'],
    },
    localIntro: {
      tag: 'FÁBRICA LOCAL EM BARUERI',
      title: 'Vidraçaria de Alto Padrão em Barueri e Alphaville',
      paragraphs: [
        'Com base em Alphaville Industrial, atendemos Barueri com agilidade — de guarda-corpos, box e espelhos residenciais em Alphaville e Tamboré a fachadas de vidro e divisórias de edifícios corporativos.',
        'Instalamos com fixação invisível por canalete, vidros laminados de segurança e içamento seguro de grandes painéis, com suporte técnico presencial e faturamento direto.',
      ],
      bullets: ['Sede na Al. Rio Negro, Alphaville', 'Guarda-corpos, box e espelhos', 'Fachadas e divisórias corporativas', 'Faturamento direto de fábrica'],
    },
    headers: {
      servicesTitle: 'Vidraçaria em Barueri SP: Serviços de Alto Padrão',
      servicesSubtitle: 'Da residência de condomínio à torre corporativa, executamos guarda-corpos, pele de vidro, box e espelhos em Barueri com a agilidade de fábrica local.',
      linesTitle: 'Tipos de Vidro Premium para Obras em Barueri',
      linesSubtitle: 'Do extra clear ao laminado de segurança e controle solar, escolha a tecnologia ideal para a sua obra em Barueri.',
      casesTitle: 'Projetos de Vidraçaria Entregues em Barueri e Alphaville',
      casesSubtitle: 'Guarda-corpos, fachadas e espelhos executados em condomínios e empreendimentos de Barueri.',
      testimonialsTitle: 'Quem Contratou Vidraçaria em Barueri Aprova',
      testimonialsSubtitle: 'Clientes e arquitetos de Barueri e Alphaville comentam a transparência e a segurança.',
      faqTitle: 'Dúvidas sobre Vidraçaria em Barueri',
      faqSubtitle: 'Respostas sobre guarda-corpos, box e espelhos em Barueri, Alphaville e Tamboré.',
      contactTitle: 'Peça um Orçamento de Vidraçaria em Barueri SP',
      contactSubtitle: 'Estamos na sua cidade, em Alphaville. Fale com o comercial técnico no WhatsApp e agende a medição.',
    },
    cases: [
      { title: 'Guarda-Corpo Autoportante - Alphaville (Barueri)', region: 'Alphaville - Barueri', description: 'Guarda-corpo de vidro laminado com canalete embutido, sem colunas, para sacada de residência de alto padrão.', image: IMG.vidro, highlight: 'Fixação Invisível' },
      { title: 'Fachada de Vidro - Alphaville Industrial (Barueri)', region: 'Alphaville Industrial - Barueri', description: 'Fachada em pele de vidro com controle solar para sede corporativa, reduzindo o calor e o consumo de energia.', image: IMG.facade, highlight: 'Controle Térmico' },
      { title: 'Espelhos e Box - Tamboré (Barueri)', region: 'Tamboré - Barueri', description: 'Box de banheiro premium com roldanas de inox e espelhos de cristal com iluminação para apartamento de luxo.', image: IMG.house, highlight: 'Box e Espelhos' },
    ],
    testimonials: [
      { author: 'Ricardo Fontes', role: 'Proprietário em Alphaville, Barueri', text: 'Como a fábrica é aqui do lado, mediram e instalaram o guarda-corpo rapidinho. Ficou clean e muito seguro.' },
      { author: 'Eng. Tatiana Lopes', role: 'Construtora em Barueri', text: 'Fizeram a fachada de vidro do nosso corporativo com içamento profissional e prazo cumprido. Excelente parceiro em Barueri.' },
    ],
    faqs: [
      { question: 'A fábrica de vidraçaria fica em Barueri?', answer: 'Sim, na Alameda Rio Negro, 229, Alphaville Industrial, Barueri, o que garante medição, fabricação e instalação ágeis para qualquer obra na cidade.' },
      { question: 'Atendem residências e obras corporativas em Barueri?', answer: 'Sim. Fazemos guarda-corpos, box e espelhos residenciais em Alphaville e Tamboré e também fachadas de vidro e divisórias corporativas.' },
      { question: 'O guarda-corpo de vidro é seguro?', answer: 'Sim, usamos vidro laminado temperado conforme a NBR 14718, com fixação invisível por canalete embutido.' },
      { question: 'Vocês fazem içamento de vidros grandes em Barueri?', answer: 'Sim, com ventosas a vácuo e equipe certificada em trabalho em altura, garantindo segurança total no içamento de painéis jumbo.' },
    ],
  },
  {
    slug: 'vidracaria-em-cotia-sp',
    city: 'Cotia',
    keyword: 'Vidraçaria em Cotia SP',
    metaTitle: 'Vidraçaria em Cotia SP | Sacadas, Guarda-Corpo e Coberturas | Serra Ferro',
    metaDescription: 'Vidraçaria em Cotia SP para casas de condomínio na Granja Viana: fechamento de sacada, guarda-corpo de vidro e coberturas com vedação contra a chuva da mata. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • VIDRAÇARIA EM COTIA SP',
      description: 'Vidraçaria em Cotia e Granja Viana para casas de condomínio cercadas de mata: fechamento de sacada, guarda-corpos de vidro voltados ao verde e coberturas com vedação reforçada contra a chuva.',
      highlights: ['Vedação reforçada contra chuva', 'Guarda-corpo voltado ao verde', 'Fechamento de sacada e coberturas', 'Vidros laminados de segurança'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM COTIA',
      title: 'Vidraçaria em Cotia e Granja Viana para Casas de Condomínio',
      paragraphs: [
        'As casas de condomínio de Cotia e da Granja Viana, cercadas por mata, aproveitam o vidro para integrar o interior à paisagem: guarda-corpos autoportantes, fechamentos de sacada e coberturas voltadas ao jardim. Reforçamos a vedação para as chuvas intensas e a umidade da região.',
        'Instalamos vidros laminados de segurança com fixação invisível e cobertura com calhas integradas, respeitando as regras de acesso dos condomínios de Cotia.',
      ],
      bullets: ['Cobertura em Granja Viana e Caucaia do Alto', 'Guarda-corpo voltado ao paisagismo', 'Fechamento de sacada com vedação', 'Coberturas de vidro com calhas'],
    },
    headers: {
      servicesTitle: 'Vidraçaria em Cotia SP: Serviços Sob Medida',
      servicesSubtitle: 'Fechamentos de sacada, guarda-corpos de vidro e coberturas sob medida para casas de condomínio em Cotia, com vedação reforçada contra a chuva da mata.',
      linesTitle: 'Tipos de Vidro Premium para Obras em Cotia',
      linesSubtitle: 'Do laminado de segurança ao controle solar, escolha a tecnologia de vidro ideal para a sua casa em Cotia e Granja Viana.',
      casesTitle: 'Projetos de Vidraçaria Entregues em Cotia e Região',
      casesSubtitle: 'Sacadas, guarda-corpos e coberturas executados em condomínios de Cotia com vedação impecável.',
      testimonialsTitle: 'Quem Contratou Vidraçaria em Cotia Recomenda',
      testimonialsSubtitle: 'Moradores de condomínios de Cotia e Granja Viana comentam a transparência e a vedação.',
      faqTitle: 'Dúvidas sobre Vidraçaria em Cotia',
      faqSubtitle: 'Respostas técnicas sobre sacadas, guarda-corpos e coberturas de vidro em Cotia.',
      contactTitle: 'Peça um Orçamento de Vidraçaria em Cotia SP',
      contactSubtitle: 'Agende a medição da sua casa em Cotia ou Granja Viana pelo WhatsApp.',
    },
    cases: [
      { title: 'Fechamento de Sacada - Granja Viana (Cotia)', region: 'Granja Viana - Cotia', description: 'Fechamento de sacada retrátil voltado à mata, com vedação de alta densidade contra as chuvas fortes da região.', image: IMG.villa, highlight: 'Sacada Panorâmica' },
      { title: 'Guarda-Corpo de Vidro - San Fernando (Cotia)', region: 'San Fernando - Cotia', description: 'Guarda-corpo autoportante de vidro laminado voltado ao jardim, com fixação invisível e transparência total.', image: IMG.vidro, highlight: 'Vista para o Verde' },
      { title: 'Cobertura de Vidro - Caucaia do Alto (Cotia)', region: 'Caucaia do Alto - Cotia', description: 'Cobertura de área gourmet em vidro laminado com calhas integradas e vedação dupla contra infiltração.', image: IMG.facade, highlight: 'Cobertura de Vidro' },
    ],
    testimonials: [
      { author: 'Fernanda Ribeiro', role: 'Moradora de condomínio na Granja Viana, Cotia', text: 'Fechamos a sacada com vidro e a área virou um cômodo a mais, sem entrar chuva nem vento. A vista da mata continua linda.' },
      { author: 'Arq. Paulo Sérgio', role: 'Arquiteto em Cotia', text: 'Guarda-corpos de vidro voltados ao paisagismo com vedação perfeita nas coberturas. Ideal para as casas de Cotia.' },
    ],
    faqs: [
      { question: 'O fechamento de sacada veda bem a chuva em Cotia?', answer: 'Sim. Usamos vedação de alta densidade, escovas hidrófugas e drenagem, essenciais para as chuvas intensas dos condomínios de Cotia e Granja Viana cercados de mata.' },
      { question: 'O guarda-corpo de vidro atrapalha a vista do jardim?', answer: 'Ao contrário — usamos guarda-corpo autoportante com fixação invisível, que preserva totalmente a vista do verde com segurança pela NBR 14718.' },
      { question: 'Vocês atendem condomínios fechados em Cotia?', answer: 'Sim, atendemos Granja Viana, San Fernando e Caucaia do Alto, respeitando as regras de acesso e horário de obra.' },
      { question: 'Fazem coberturas de vidro em Cotia?', answer: 'Sim, executamos coberturas em vidro laminado com calhas integradas e vedação dupla, ideais para áreas gourmet voltadas ao jardim.' },
    ],
  },
  {
    slug: 'vidracaria-em-embu-das-artes-sp',
    city: 'Embu das Artes',
    keyword: 'Vidraçaria em Embu das Artes SP',
    metaTitle: 'Vidraçaria em Embu das Artes SP | Espelhos, Box e Guarda-Corpo | Serra Ferro',
    metaDescription: 'Vidraçaria em Embu das Artes SP: espelhos decorativos, box, guarda-corpo de vidro e coberturas sob medida, unindo design e vedação para casas de charme. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • VIDRAÇARIA EM EMBU DAS ARTES SP',
      description: 'Vidraçaria em Embu das Artes unindo design e desempenho: espelhos decorativos, box, guarda-corpos de vidro e coberturas sob medida para casas de campo e ateliês, com vedação para o clima úmido.',
      highlights: ['Espelhos e vidros decorativos', 'Guarda-corpo e box sob medida', 'Coberturas com vedação', 'Design para casas de charme'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM EMBU DAS ARTES',
      title: 'Vidraçaria com Design em Embu das Artes',
      paragraphs: [
        'Na cidade das artes, o vidro entra como elemento estético: espelhos de cristal decorativos, guarda-corpos que preservam a vista do verde, coberturas de vidro para áreas gourmet e box sob medida. Unimos design ao desempenho técnico e à vedação para o clima úmido e ameno de Embu das Artes.',
        'Atendemos casas de campo e ateliês em bairros como Jardim dos Manacás e Pinheirinho, com vidros laminados de segurança, fixação invisível e coberturas bem vedadas.',
      ],
      bullets: ['Espelhos de cristal decorativos', 'Guarda-corpos voltados ao jardim', 'Coberturas de vidro para gourmet', 'Cobertura em Jardim dos Manacás'],
    },
    headers: {
      servicesTitle: 'Vidraçaria em Embu das Artes SP: Design e Desempenho',
      servicesSubtitle: 'Espelhos, box, guarda-corpos de vidro e coberturas sob medida para casas de campo e residências de charme em Embu das Artes.',
      linesTitle: 'Tipos de Vidro Premium para Obras em Embu das Artes',
      linesSubtitle: 'Do extra clear ao laminado de segurança, escolha a tecnologia de vidro ideal para a estética da sua obra em Embu das Artes.',
      casesTitle: 'Projetos de Vidraçaria Entregues em Embu das Artes',
      casesSubtitle: 'Espelhos, guarda-corpos e coberturas executados em casas e ateliês de Embu das Artes.',
      testimonialsTitle: 'Quem Contratou Vidraçaria em Embu das Artes Recomenda',
      testimonialsSubtitle: 'Moradores de Embu das Artes comentam o design e a vedação dos vidros.',
      faqTitle: 'Dúvidas sobre Vidraçaria em Embu das Artes',
      faqSubtitle: 'Respostas técnicas sobre espelhos, guarda-corpos e coberturas de vidro em Embu das Artes.',
      contactTitle: 'Peça um Orçamento de Vidraçaria em Embu das Artes SP',
      contactSubtitle: 'Agende a medição da sua casa em Embu das Artes pelo WhatsApp.',
    },
    cases: [
      { title: 'Espelho Decorativo - Ateliê no Centro Histórico (Embu das Artes)', region: 'Centro Histórico - Embu das Artes', description: 'Espelho de cristal de alta definição com corte bisotê para ampliar e iluminar o espaço de criação.', image: IMG.house, highlight: 'Espelho de Cristal' },
      { title: 'Guarda-Corpo de Vidro - Jardim dos Manacás (Embu das Artes)', region: 'Jardim dos Manacás - Embu das Artes', description: 'Guarda-corpo autoportante de vidro laminado voltado ao jardim, com fixação invisível e transparência total.', image: IMG.vidro, highlight: 'Vista para o Verde' },
      { title: 'Cobertura de Vidro - Pinheirinho (Embu das Artes)', region: 'Pinheirinho - Embu das Artes', description: 'Cobertura de área gourmet em vidro laminado com vedação reforçada contra a umidade e a chuva da região.', image: IMG.facade, highlight: 'Cobertura de Vidro' },
    ],
    testimonials: [
      { author: 'Rogério Bianchi', role: 'Artista plástico em Embu das Artes', text: 'O espelho de cristal deu profundidade e luz ao ateliê. Corte perfeito e instalação caprichada.' },
      { author: 'Luciana Amaral', role: 'Moradora do Jardim dos Manacás, Embu das Artes', text: 'O guarda-corpo de vidro e a cobertura ficaram lindos e não entra chuva. Uniram estética e vedação como eu queria.' },
    ],
    faqs: [
      { question: 'Os espelhos de cristal mancham com o tempo?', answer: 'Não. Trabalhamos com espelhos de cristal com proteção contra umidade e usamos colas de cura neutra, evitando oxidação — importante no clima úmido de Embu das Artes.' },
      { question: 'O guarda-corpo de vidro preserva a vista do jardim?', answer: 'Sim, usamos guarda-corpo autoportante com fixação invisível e vidro laminado seguro pela NBR 14718, mantendo total transparência.' },
      { question: 'As coberturas de vidro vedam bem no clima úmido?', answer: 'Sim, executamos coberturas com vidro laminado, calhas integradas e vedação dupla contra infiltrações e a umidade da região.' },
      { question: 'Atendem casas de campo e ateliês em Embu das Artes?', answer: 'Sim, atendemos casas, ateliês e condomínios da cidade com medição no local e instalação por equipe própria.' },
    ],
  },
  {
    slug: 'vidracaria-em-taboao-da-serra-sp',
    city: 'Taboão da Serra',
    keyword: 'Vidraçaria em Taboão da Serra SP',
    metaTitle: 'Vidraçaria em Taboão da Serra SP | Box, Espelhos e Guarda-Corpo | Serra Ferro',
    metaDescription: 'Vidraçaria em Taboão da Serra SP para casas e reformas: box de banheiro, espelhos, guarda-corpo de vidro e divisórias sob medida com fixação invisível. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • VIDRAÇARIA EM TABOÃO DA SERRA SP',
      description: 'Vidraçaria em Taboão da Serra para casas, sobrados e reformas: box de banheiro, espelhos, guarda-corpos de vidro e divisórias sob medida, com fixação invisível e instalação limpa.',
      highlights: ['Box premium e espelhos', 'Guarda-corpo e divisórias', 'Ideal para reforma', 'Instalação limpa e rápida'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM TABOÃO DA SERRA',
      title: 'Vidraçaria em Taboão da Serra para Casas e Reformas',
      paragraphs: [
        'Colada à capital, Taboão da Serra tem muitos sobrados e apartamentos em reforma, onde o vidro renova o acabamento: box de banheiro, espelhos, guarda-corpos de escada e divisórias que ampliam e iluminam os ambientes.',
        'Somos especialistas em reforma: medimos com precisão, instalamos vidros temperados e laminados de segurança com roldanas de inox e fixação invisível, sem sujeira e no prazo.',
      ],
      bullets: ['Box de banheiro com inox', 'Espelhos e divisórias de vidro', 'Guarda-corpos de escada', 'Atendimento no Pirajuçara e centro'],
    },
    headers: {
      servicesTitle: 'Vidraçaria em Taboão da Serra SP: Serviços Sob Medida',
      servicesSubtitle: 'Box, espelhos, guarda-corpos de vidro e divisórias sob medida para casas e reformas em Taboão da Serra, com fixação invisível.',
      linesTitle: 'Tipos de Vidro Premium para Obras em Taboão da Serra',
      linesSubtitle: 'Do temperado ao laminado de segurança, escolha a tecnologia de vidro ideal para o seu imóvel em Taboão da Serra.',
      casesTitle: 'Projetos de Vidraçaria Entregues em Taboão da Serra',
      casesSubtitle: 'Boxes, espelhos e guarda-corpos executados em casas e sobrados de Taboão da Serra.',
      testimonialsTitle: 'Quem Contratou Vidraçaria em Taboão da Serra Aprova',
      testimonialsSubtitle: 'Moradores de Taboão da Serra comentam o acabamento e a agilidade da instalação.',
      faqTitle: 'Dúvidas sobre Vidraçaria em Taboão da Serra',
      faqSubtitle: 'Respostas para box, espelhos e guarda-corpos em Taboão da Serra.',
      contactTitle: 'Peça um Orçamento de Vidraçaria em Taboão da Serra SP',
      contactSubtitle: 'Agende a medição do seu imóvel em Taboão da Serra e fale com o comercial pelo WhatsApp.',
    },
    cases: [
      { title: 'Box e Espelhos - Reforma em Jardim Henriqueta (Taboão da Serra)', region: 'Jardim Henriqueta - Taboão da Serra', description: 'Box de banheiro premium com roldanas de inox e espelhos lapidados, instalados em reforma com acabamento impecável.', image: IMG.vidro, highlight: 'Box Premium' },
      { title: 'Divisória de Vidro - Pirajuçara (Taboão da Serra)', region: 'Pirajuçara - Taboão da Serra', description: 'Divisória de vidro temperado separando ambientes com elegância e luz em apartamento reformado.', image: IMG.min, highlight: 'Divisória' },
      { title: 'Guarda-Corpo de Escada - Parque Assunção (Taboão da Serra)', region: 'Parque Assunção - Taboão da Serra', description: 'Guarda-corpo de vidro laminado para escada de sobrado, com fixação por botões de inox e transparência total.', image: IMG.house, highlight: 'Guarda-Corpo' },
    ],
    testimonials: [
      { author: 'Sandra Prado', role: 'Moradora do Jardim Henriqueta, Taboão da Serra', text: 'Reformei o banheiro e o box com espelho novo transformou o ambiente. Instalação limpa e rápida, sem quebrar nada.' },
      { author: 'Wagner Lima', role: 'Proprietário de sobrado em Taboão da Serra', text: 'O guarda-corpo de vidro da escada ficou moderno e seguro. Ótimo acabamento por um preço justo.' },
    ],
    faqs: [
      { question: 'Vocês fazem só a parte de vidro na reforma em Taboão da Serra?', answer: 'Sim. Somos especialistas em reforma: medimos, fabricamos e instalamos box, espelhos, guarda-corpos e divisórias com instalação limpa, sem danificar o acabamento pronto.' },
      { question: 'O box tem boas roldanas?', answer: 'Sim, usamos roldanas de inox de alta durabilidade e vidros temperados de segurança, com acabamento premium.' },
      { question: 'O guarda-corpo de vidro da escada é seguro?', answer: 'Sim, usamos vidro laminado conforme a NBR 14718, com fixação por botões de inox ou canalete, garantindo segurança total.' },
      { question: 'Atendem apartamentos e sobrados em Taboão da Serra?', answer: 'Sim, atendemos casas, sobrados e apartamentos, do Pirajuçara ao centro, respeitando as regras dos condomínios.' },
    ],
  },
  {
    slug: 'vidracaria-em-osasco-sp',
    city: 'Osasco',
    keyword: 'Vidraçaria em Osasco SP',
    metaTitle: 'Vidraçaria em Osasco SP | Sacadas, Guarda-Corpo e Fachadas | Serra Ferro',
    metaDescription: 'Vidraçaria em Osasco SP para torres e casas: fechamento de sacada, guarda-corpo de vidro, box, espelhos e fachadas de vidro sob medida com segurança em altura. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • VIDRAÇARIA EM OSASCO SP',
      description: 'Vidraçaria em Osasco para torres e residências: fechamento de sacada, guarda-corpos de vidro, box, espelhos e fachadas de vidro sob medida, com segurança e vedação mesmo em andares altos.',
      highlights: ['Fechamento de sacada em torres', 'Guarda-corpo pela NBR 14718', 'Box, espelhos e fachadas', 'Segurança em altura'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM OSASCO',
      title: 'Vidraçaria em Osasco para Torres e Residências',
      paragraphs: [
        'Verticalizada e movimentada, Osasco demanda vidraçaria para torres: fechamentos de sacada, guarda-corpos de varanda e fachadas de vidro em bairros como Bela Vista, Vila Yara e Km 18, além de box e espelhos residenciais.',
        'Instalamos guarda-corpos dimensionados pela NBR 14718 e fechamentos com vedação reforçada para os andares altos, expostos ao vento, com içamento seguro dos painéis.',
      ],
      bullets: ['Fechamento de sacada em altura', 'Guarda-corpos de varanda com norma', 'Fachadas de vidro e box', 'Cobertura na Bela Vista e Km 18'],
    },
    headers: {
      servicesTitle: 'Vidraçaria em Osasco SP: Serviços de Alto Padrão',
      servicesSubtitle: 'Fechamentos de sacada, guarda-corpos, fachadas de vidro, box e espelhos sob medida para torres e residências de Osasco, com segurança em altura.',
      linesTitle: 'Tipos de Vidro Premium para Obras em Osasco',
      linesSubtitle: 'Do laminado de segurança ao controle solar, escolha a tecnologia de vidro ideal para a sua obra em Osasco.',
      casesTitle: 'Projetos de Vidraçaria Entregues em Osasco',
      casesSubtitle: 'Sacadas, guarda-corpos e fachadas executados em torres e casas de Osasco.',
      testimonialsTitle: 'Quem Contratou Vidraçaria em Osasco Aprova',
      testimonialsSubtitle: 'Moradores e síndicos de Osasco comentam a segurança e a vedação dos vidros.',
      faqTitle: 'Dúvidas sobre Vidraçaria em Osasco',
      faqSubtitle: 'Respostas técnicas sobre sacadas, guarda-corpos e fachadas de vidro em Osasco.',
      contactTitle: 'Peça um Orçamento de Vidraçaria em Osasco SP',
      contactSubtitle: 'Agende a visita técnica do seu apartamento ou edifício em Osasco pelo WhatsApp.',
    },
    cases: [
      { title: 'Fechamento de Sacada - Bela Vista (Osasco)', region: 'Bela Vista - Osasco', description: 'Fechamento de sacada em vidro temperado para apartamento alto, com roldanas ocultas e vedação reforçada contra o vento.', image: IMG.villa, highlight: 'Sacada em Altura' },
      { title: 'Guarda-Corpo de Varanda - Centro (Osasco)', region: 'Centro - Osasco', description: 'Guarda-corpo de vidro laminado para varanda de torre, dimensionado pela NBR 14718 com fixação segura.', image: IMG.vidro, highlight: 'Norma NBR 14718' },
      { title: 'Box e Espelhos - Vila Yara (Osasco)', region: 'Vila Yara - Osasco', description: 'Box de banheiro premium e espelhos lapidados para residência, com roldanas de inox e acabamento fino.', image: IMG.house, highlight: 'Box e Espelhos' },
    ],
    testimonials: [
      { author: 'Patrícia Gomes', role: 'Moradora da Bela Vista, Osasco', text: 'Fechei a sacada do apartamento alto e o vento parou de incomodar. Vedação perfeita e vista preservada.' },
      { author: 'Eng. Roberto Dias', role: 'Síndico de edifício no Centro de Osasco', text: 'Os guarda-corpos de vidro das varandas foram feitos dentro da norma, com içamento seguro. Trabalho muito profissional.' },
    ],
    faqs: [
      { question: 'O fechamento de sacada aguenta o vento dos andares altos em Osasco?', answer: 'Sim. Reforçamos a vedação e usamos vidros temperados adequados, garantindo estanqueidade e segurança mesmo nos andares altos e expostos de Osasco.' },
      { question: 'Os guarda-corpos de varanda atendem à NBR 14718?', answer: 'Sim, dimensionamos os guarda-corpos de vidro pelos esforços da norma NBR 14718, essenciais para varandas de torres.' },
      { question: 'Vocês fazem içamento de vidro em prédios de Osasco?', answer: 'Sim, com ventosas a vácuo e equipe certificada em trabalho em altura (NR-35), garantindo segurança total no içamento.' },
      { question: 'Atendem também casas em Osasco?', answer: 'Sim, fazemos box, espelhos e guarda-corpos residenciais em bairros como Vila Yara e Km 18.' },
    ],
  },
  {
    slug: 'vidracaria-em-jandira-sp',
    city: 'Jandira',
    keyword: 'Vidraçaria em Jandira SP',
    metaTitle: 'Vidraçaria em Jandira SP | Box, Espelhos e Guarda-Corpo | Serra Ferro',
    metaDescription: 'Vidraçaria em Jandira SP para casas, sobrados e reformas: box de banheiro, espelhos, guarda-corpo de vidro e divisórias sob medida com ótimo custo-benefício. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • VIDRAÇARIA EM JANDIRA SP',
      description: 'Vidraçaria em Jandira para casas, sobrados e reformas: box de banheiro, espelhos, guarda-corpos de vidro e divisórias sob medida, com excelente custo-benefício e fixação invisível.',
      highlights: ['Ótimo custo-benefício', 'Box premium e espelhos', 'Guarda-corpo e divisórias', 'Ideal para reforma'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM JANDIRA',
      title: 'Vidraçaria em Jandira com Custo-Benefício e Acabamento Fino',
      paragraphs: [
        'Cidade compacta do oeste da Grande São Paulo, Jandira reúne casas e sobrados em bairros como Jardim Sabará e Vila Eutália. Entregamos box, espelhos, guarda-corpos e divisórias de vidro com excelente custo-benefício, sem abrir mão da segurança e do acabamento fino.',
        'Somos especialistas em reforma e instalação de vidros em obra pronta, com medição precisa, roldanas de inox nos boxes e fixação invisível nos guarda-corpos.',
      ],
      bullets: ['Excelente custo-benefício', 'Box de banheiro com inox', 'Espelhos e divisórias de vidro', 'Cobertura no Jardim Sabará e Vila Eutália'],
    },
    headers: {
      servicesTitle: 'Vidraçaria em Jandira SP: Serviços Sob Medida',
      servicesSubtitle: 'Box, espelhos, guarda-corpos de vidro e divisórias sob medida para casas, sobrados e reformas em Jandira, com ótimo custo-benefício.',
      linesTitle: 'Tipos de Vidro Premium para Obras em Jandira',
      linesSubtitle: 'Do temperado ao laminado de segurança, escolha a tecnologia de vidro ideal para o seu imóvel em Jandira.',
      casesTitle: 'Projetos de Vidraçaria Entregues em Jandira',
      casesSubtitle: 'Boxes, espelhos e guarda-corpos executados em casas e sobrados de Jandira com bom custo-benefício.',
      testimonialsTitle: 'Quem Contratou Vidraçaria em Jandira Aprova',
      testimonialsSubtitle: 'Moradores de Jandira comentam o custo-benefício e o acabamento dos vidros.',
      faqTitle: 'Dúvidas sobre Vidraçaria em Jandira',
      faqSubtitle: 'Respostas para box, espelhos e guarda-corpos em Jandira.',
      contactTitle: 'Peça um Orçamento de Vidraçaria em Jandira SP',
      contactSubtitle: 'Agende a medição da sua casa ou sobrado em Jandira pelo WhatsApp.',
    },
    cases: [
      { title: 'Box e Espelho - Jardim Sabará (Jandira)', region: 'Jardim Sabará - Jandira', description: 'Box de banheiro com roldanas de inox e espelho lapidado sob medida, com ótimo custo-benefício e acabamento fino.', image: IMG.vidro, highlight: 'Custo-Benefício' },
      { title: 'Divisória de Vidro - Vila Eutália (Jandira)', region: 'Vila Eutália - Jandira', description: 'Divisória de vidro temperado separando ambientes com luz e elegância em sobrado.', image: IMG.min, highlight: 'Divisória' },
      { title: 'Guarda-Corpo de Vidro - Centro (Jandira)', region: 'Centro - Jandira', description: 'Guarda-corpo de vidro laminado para escada, com fixação por botões de inox e transparência total.', image: IMG.house, highlight: 'Guarda-Corpo' },
    ],
    testimonials: [
      { author: 'Juliana Freitas', role: 'Moradora do Jardim Sabará, Jandira', text: 'Troquei o box e coloquei espelho novo por um preço muito bom. Ficou com cara de banheiro de revista.' },
      { author: 'Marcos Aurélio', role: 'Proprietário de sobrado em Jandira', text: 'O guarda-corpo de vidro da escada deixou tudo mais moderno e seguro. Ótimo acabamento pelo valor.' },
    ],
    faqs: [
      { question: 'A vidraçaria da Serra-Ferro tem bom custo-benefício para Jandira?', answer: 'Sim. Entregamos box, espelhos, guarda-corpos e divisórias com excelente custo-benefício, mantendo os vidros de segurança e o acabamento fino da Serra-Ferro.' },
      { question: 'Vocês fazem a parte de vidro só na reforma em Jandira?', answer: 'Sim, somos especialistas em reforma: medimos, fabricamos e instalamos com instalação limpa, sem danificar o acabamento pronto.' },
      { question: 'O box tem boas roldanas?', answer: 'Sim, usamos roldanas de inox de alta durabilidade e vidros temperados de segurança.' },
      { question: 'O guarda-corpo de vidro é seguro?', answer: 'Sim, usamos vidro laminado conforme a NBR 14718, com fixação por botões de inox ou canalete.' },
    ],
  },
  {
    slug: 'vidracaria-em-santana-de-parnaiba-sp',
    city: 'Santana de Parnaíba',
    keyword: 'Vidraçaria em Santana de Parnaíba SP',
    metaTitle: 'Vidraçaria em Santana de Parnaíba SP | Guarda-Corpo e Sacadas | Serra Ferro',
    metaDescription: 'Vidraçaria em Santana de Parnaíba SP para os condomínios de Alphaville: guarda-corpo de vidro, fechamento de sacada e coberturas calculados para vento, com vidros de segurança. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • VIDRAÇARIA EM SANTANA DE PARNAÍBA SP',
      description: 'Vidraçaria em Santana de Parnaíba para condomínios de Alphaville e casarões: guarda-corpos de vidro, fechamentos de sacada e coberturas calculados para o vento das áreas altas, com vidros de segurança.',
      highlights: ['Vidros calculados para vento', 'Guarda-corpo pela NBR 14718', 'Fechamento de sacada e coberturas', 'Condomínios de Alphaville Residencial'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM SANTANA DE PARNAÍBA',
      title: 'Vidraçaria em Santana de Parnaíba e Alphaville Residencial',
      paragraphs: [
        'Santana de Parnaíba abriga residenciais de Alphaville e casarões em áreas elevadas, onde guarda-corpos de vidro, fechamentos de sacada e coberturas precisam suportar cargas de vento maiores. Dimensionamos as espessuras e fixações pela NBR 14718, preservando a vista sem abrir mão da segurança.',
        'Do centro histórico aos condomínios contemporâneos, instalamos vidros laminados de segurança, coberturas bem vedadas e espelhos monumentais, com içamento seguro dos painéis.',
      ],
      bullets: ['Residenciais Alphaville e Tamboré', 'Guarda-corpos e sacadas para vento', 'Coberturas de vidro vedadas', 'Espelhos monumentais'],
    },
    headers: {
      servicesTitle: 'Vidraçaria em Santana de Parnaíba SP: Alto Padrão',
      servicesSubtitle: 'Guarda-corpos de vidro, fechamentos de sacada, coberturas e espelhos sob medida para casarões e condomínios de Santana de Parnaíba, calculados para vento.',
      linesTitle: 'Tipos de Vidro Premium para Obras em Santana de Parnaíba',
      linesSubtitle: 'Do laminado de segurança ao controle solar, escolha a tecnologia de vidro ideal para áreas expostas ao vento.',
      casesTitle: 'Projetos de Vidraçaria Entregues em Santana de Parnaíba',
      casesSubtitle: 'Guarda-corpos, sacadas e coberturas executados nos condomínios de Alphaville Residencial e região.',
      testimonialsTitle: 'Quem Contratou Vidraçaria em Santana de Parnaíba Recomenda',
      testimonialsSubtitle: 'Moradores dos condomínios de Santana de Parnaíba comentam a segurança e a vedação dos vidros.',
      faqTitle: 'Dúvidas sobre Vidraçaria em Santana de Parnaíba',
      faqSubtitle: 'Respostas técnicas sobre guarda-corpos, sacadas e coberturas de vidro na região.',
      contactTitle: 'Peça um Orçamento de Vidraçaria em Santana de Parnaíba SP',
      contactSubtitle: 'Agende a visita técnica do seu casarão ou residência em Santana de Parnaíba pelo WhatsApp.',
    },
    cases: [
      { title: 'Guarda-Corpo Autoportante - Alphaville (Santana de Parnaíba)', region: 'Alphaville - Santana de Parnaíba', description: 'Guarda-corpo de vidro laminado temperado dimensionado para o vento das áreas altas, sem colunas, preservando a vista.', image: IMG.vidro, highlight: 'Reforço de Vento' },
      { title: 'Fechamento de Sacada - Tamboré (Santana de Parnaíba)', region: 'Tamboré - Santana de Parnaíba', description: 'Fechamento de sacada panorâmica com vedação de alta densidade contra a chuva com vento das áreas elevadas.', image: IMG.villa, highlight: 'Sacada Panorâmica' },
      { title: 'Espelho Monumental - Centro Histórico (Santana de Parnaíba)', region: 'Centro Histórico - Santana de Parnaíba', description: 'Espelho de cristal de alta definição com corte bisotê para casarão, ampliando e iluminando o ambiente.', image: IMG.house, highlight: 'Espelho de Cristal' },
    ],
    testimonials: [
      { author: 'Marcelo Tavares', role: 'Morador de Alphaville, Santana de Parnaíba', text: 'O guarda-corpo de vidro aguenta o vento forte da região sem vibrar e mantém a vista aberta. Segurança e beleza juntas.' },
      { author: 'Arq. Beatriz Nunes', role: 'Arquiteta em Santana de Parnaíba', text: 'Dimensionaram os vidros pela norma considerando o vento e o fechamento de sacada ficou impecável, sem vazar.' },
    ],
    faqs: [
      { question: 'O guarda-corpo de vidro aguenta o vento das áreas altas de Santana de Parnaíba?', answer: 'Sim. Calculamos a espessura do vidro e as fixações pela NBR 14718 considerando as cargas de vento do relevo, garantindo segurança e estabilidade.' },
      { question: 'Vocês atendem os condomínios de Alphaville em Santana de Parnaíba?', answer: 'Sim, atendemos Alphaville, Tamboré e demais condomínios da cidade, respeitando as regras de acesso e horário de obra.' },
      { question: 'O fechamento de sacada veda a chuva com vento?', answer: 'Sim, usamos vedação de alta densidade e drenagem, essenciais para as sacadas expostas dos condomínios elevados da região.' },
      { question: 'Fazem espelhos monumentais e coberturas de vidro?', answer: 'Sim, fabricamos espelhos de cristal sob medida e coberturas de vidro laminado com vedação dupla contra infiltrações.' },
    ],
  },
];

export const VIDRACARIA_REGION_BY_SLUG: Record<string, RegionPage> = Object.fromEntries(
  VIDRACARIA_REGIONS.map((r) => [r.slug, r]),
);
