/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// Páginas regionais de Serralheria. Copy ~80% única por cidade, reutilizando a estrutura
// de seções da página de Serralheria (CategoryPillar) via a prop `region`.

import { RegionPage } from './regionsEsquadrias';

const IMG = {
  esq: '/assets/images/esquadrias_aluminio_luxury_card_1782739998198.jpg',
  villa: '/assets/images/luxury_villa_glazing_1782306007983.jpg',
  min: '/assets/images/minimal_aluminum_frames_1782306022668.jpg',
  facade: '/assets/images/modern_facade_glass_1782306036555.jpg',
  house: '/assets/images/portfolio_house_luxury_card_1782740031450.jpg',
  vidro: '/assets/images/vidracaria_balcony_luxury_card_1782740008784.jpg',
  serr: '/assets/images/serralheria_staircase_luxury_card_1782740019768.jpg',
};

export const SERRALHERIA_SP_SLUG = 'serralheria-em-sao-paulo-sp';

export const SERRALHERIA_REGIONS: RegionPage[] = [
  {
    slug: 'serralheria-em-alphaville-sp',
    city: 'Alphaville',
    keyword: 'Serralheria em Alphaville SP',
    metaTitle: 'Serralheria em Alphaville SP | Escadas, Portões e Estruturas | Serra Ferro',
    metaDescription: 'Serralheria fina em Alphaville SP: escadas de design, portões monumentais e estruturas metálicas sob medida com solda invisível. Fábrica na região. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • SERRALHERIA EM ALPHAVILLE SP',
      description: 'Serralheria fina em Alphaville com fábrica na própria região: escadas esculturais, portões monumentais e mezaninos calculados, com solda 100% invisível e acabamento de altíssimo padrão.',
      highlights: ['Fábrica na região de Alphaville', 'Solda invisível ao toque', 'Escadas e portões de design', 'Cálculo estrutural com ART'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM ALPHAVILLE',
      title: 'Serralheria Fina em Alphaville para Projetos de Altíssimo Padrão',
      paragraphs: [
        'Alphaville concentra residências contemporâneas que pedem serralheria de autor: escadas plissadas ou helicoidais, portões de entrada monumentais e brises geométricos. Com a nossa fábrica na própria região, executamos cada peça com solda lixada e invisível ao toque e acabamento em pintura eletrostática microtexturizada de longa durabilidade.',
        'Trabalhamos junto aos arquitetos dos condomínios de Alphaville, detalhando em CAD as estruturas e emitindo ART quando há cálculo de carga. O resultado une estética marcante e engenharia — de mezaninos de mezanino social a corrimãos milimétricos.',
      ],
      bullets: ['Sede em Alphaville Industrial, Barueri', 'Escadas helicoidais e plissadas', 'Portões e brises de design autoral', 'Projeto executivo em CAD com ART'],
    },
    headers: {
      servicesTitle: 'Serralheria em Alphaville SP: Serviços de Alto Padrão',
      servicesSubtitle: 'Escadas esculturais, portões monumentais, mezaninos e brises sob medida para as residências de altíssimo padrão de Alphaville, com solda invisível.',
      linesTitle: 'Linhas de Serralheria para Obras em Alphaville',
      linesSubtitle: 'Da serralheria fina ao aço estrutural pesado, escolha a linha ideal para o design e a carga da sua obra em Alphaville.',
      casesTitle: 'Projetos de Serralheria Entregues em Alphaville',
      casesSubtitle: 'Escadas de design e estruturas metálicas executadas nos condomínios de Alphaville com acabamento artesanal.',
      testimonialsTitle: 'Quem Contratou Serralheria em Alphaville Recomenda',
      testimonialsSubtitle: 'Moradores e arquitetos de Alphaville comentam o acabamento e a precisão das nossas peças.',
      faqTitle: 'Dúvidas sobre Serralheria em Alphaville',
      faqSubtitle: 'Respostas técnicas para escadas, portões e estruturas metálicas em Alphaville.',
      contactTitle: 'Peça um Orçamento de Serralheria em Alphaville SP',
      contactSubtitle: 'Estamos na região de Alphaville. Fale com o comercial técnico no WhatsApp e tire seu projeto de aço do papel.',
    },
    cases: [
      { title: 'Escada Helicoidal - Residencial Alphaville', region: 'Alphaville', description: 'Escada helicoidal metálica com solda invisível e degraus em chapa dobrada, com pintura epóxi fosca de alta durabilidade.', image: IMG.serr, highlight: 'Escada Helicoidal' },
      { title: 'Portão Monumental - Alphaville', region: 'Alphaville', description: 'Portão pivotante de entrada em aço com revestimento corten, deslizamento leve e estrutura anti-empenamento para grandes vãos.', image: IMG.house, highlight: 'Portão de Design' },
      { title: 'Mezanino Social - Alphaville', region: 'Alphaville', description: 'Mezanino com vigas metálicas aparentes e guarda-corpo de aço e vidro, calculado por engenharia e com ART.', image: IMG.min, highlight: 'Mezanino Calculado' },
    ],
    testimonials: [
      { author: 'Henrique Salles', role: 'Morador de Alphaville', text: 'A escada da minha casa virou a peça central da sala. Solda invisível de verdade, acabamento impecável e montagem limpa dentro do condomínio.' },
      { author: 'Arq. Camila Prado', role: 'Arquiteta em Alphaville', text: 'Detalharam a serralheria em CAD exatamente como desenhei e ainda entregaram a ART do mezanino. Parceria técnica de altíssimo nível.' },
      { author: 'Eng. Marcelo Franco', role: 'Construtora em Alphaville', text: 'Estruturas e escadas entregues com ART e solda invisível. A fábrica local de Alphaville deixa o cronograma redondo, sem atrasos.' },
    ],
    faqs: [
      { question: 'A solda das escadas fica realmente invisível?', answer: 'Sim. Em Alphaville, onde o acabamento é decisivo, lixamos e tratamos cada solda até ficar invisível ao toque, finalizando com pintura eletrostática a pó curada em forno para máxima durabilidade.' },
      { question: 'Vocês emitem ART para mezaninos e estruturas em Alphaville?', answer: 'Sim. Mezaninos, escadas monumentais e coberturas metálicas são calculados por engenheiro e acompanham ART registrada no CREA, garantindo a segurança estrutural da obra.' },
      { question: 'A fábrica fica perto de Alphaville?', answer: 'Fica em Alphaville Industrial, Barueri, na própria região — o que agiliza medição, fabricação e instalação, além do suporte técnico presencial.' },
      { question: 'Vocês trabalham com aço corten em Alphaville?', answer: 'Sim. O aço corten é muito procurado em Alphaville pelo visual contemporâneo. Fornecemos portões, painéis e brises em corten legítimo, com pátina natural controlada e sem manutenção periódica.' },
      { question: 'Qual a garantia da serralheria em Alphaville?', answer: 'Oferecemos garantia contratual sobre a execução, o tratamento anticorrosivo e a estabilidade estrutural das peças, com laudos e ART quando há cálculo de carga.' },
    ],
  },
  {
    slug: 'serralheria-em-cajamar-sp',
    city: 'Cajamar',
    keyword: 'Serralheria em Cajamar SP',
    metaTitle: 'Serralheria em Cajamar SP | Estruturas, Portões e Escadas | Serra Ferro',
    metaDescription: 'Serralheria em Cajamar SP: estruturas metálicas, portões e escadas sob medida com tratamento anticorrosivo reforçado e cálculo para relevo e vento. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • SERRALHERIA EM CAJAMAR SP',
      description: 'Serralheria em Cajamar para condomínios de alto padrão e galpões: estruturas metálicas, portões e escadas calculados para o relevo e o vento da região, com tratamento anticorrosivo severo.',
      highlights: ['Cálculo estrutural para vento', 'Tratamento anticorrosivo reforçado', 'Condomínios e uso logístico', 'Solda fina e pintura durável'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM CAJAMAR',
      title: 'Serralheria em Cajamar para Condomínios em Relevo e Galpões',
      paragraphs: [
        'Cajamar combina condomínios de alto padrão em áreas de relevo, como a Reserva Santa Maria, com um forte polo logístico em Polvilho e Jordanésia. Executamos desde escadas e guarda-corpos metálicos residenciais até estruturas e coberturas de galpão, sempre com cálculo para as cargas de vento das áreas elevadas.',
        'Aplicamos tratamento anticorrosivo severo — galvanização e pintura eletrostática — indispensável para a durabilidade em terrenos altos e expostos. Entregamos com solda fina, projeto executivo e ART quando o porte exige.',
      ],
      bullets: ['Cobertura em Polvilho e Jordanésia', 'Estruturas e coberturas de galpão', 'Galvanização contra corrosão', 'Cálculo de vento para relevo'],
    },
    headers: {
      servicesTitle: 'Serralheria em Cajamar SP: Estruturas e Serralheria Fina',
      servicesSubtitle: 'Estruturas metálicas, portões, escadas e mezaninos sob medida para condomínios e galpões de Cajamar, com tratamento anticorrosivo reforçado.',
      linesTitle: 'Linhas de Serralheria para Obras em Cajamar',
      linesSubtitle: 'Do aço estrutural pesado à serralheria fina, escolha a linha compatível com a carga e o acabamento da sua obra em Cajamar.',
      casesTitle: 'Projetos de Serralheria Entregues em Cajamar',
      casesSubtitle: 'Estruturas e peças metálicas executadas em condomínios e áreas logísticas de Cajamar com durabilidade comprovada.',
      testimonialsTitle: 'Quem Contratou Serralheria em Cajamar Recomenda',
      testimonialsSubtitle: 'Clientes de Cajamar comentam a robustez, o acabamento e a resistência à corrosão.',
      faqTitle: 'Dúvidas sobre Serralheria em Cajamar',
      faqSubtitle: 'Respostas técnicas para estruturas, portões e escadas em Cajamar, Polvilho e Jordanésia.',
      contactTitle: 'Peça um Orçamento de Serralheria em Cajamar SP',
      contactSubtitle: 'Agende a visita técnica da sua obra em Cajamar e fale com o nosso engenheiro comercial pelo WhatsApp.',
    },
    cases: [
      { title: 'Cobertura Metálica - Galpão em Polvilho (Cajamar)', region: 'Polvilho - Cajamar', description: 'Estrutura de cobertura em aço com telha termoacústica, dimensionada para as cargas de vento da região e com galvanização anticorrosiva.', image: IMG.min, highlight: 'Estrutura de Galpão' },
      { title: 'Escada e Guarda-Corpo - Reserva Santa Maria (Cajamar)', region: 'Reserva Santa Maria - Cajamar', description: 'Escada metálica com guarda-corpo de aço e vidro para residência em aclive, com solda fina e pintura de alta durabilidade.', image: IMG.serr, highlight: 'Escada Residencial' },
      { title: 'Portão Reforçado - Jordanésia (Cajamar)', region: 'Jordanésia - Cajamar', description: 'Portão deslizante automático em chapa de aço para terreno em declive, com motor de alta resistência e tratamento antiferrugem.', image: IMG.house, highlight: 'Portão Automático' },
    ],
    testimonials: [
      { author: 'Vinícius Barros', role: 'Morador da Reserva Santa Maria, Cajamar', text: 'A casa fica numa parte alta e úmida. O portão e o guarda-corpo de aço não deram um ponto de ferrugem — o tratamento deles é diferenciado.' },
      { author: 'Eng. Fábio Assis', role: 'Responsável por galpão em Polvilho, Cajamar', text: 'Executaram a cobertura metálica no prazo e com ART. Estrutura robusta, montagem organizada e zero retrabalho.' },
      { author: 'Arq. Larissa Prado', role: 'Arquiteta em Cajamar', text: 'Especifiquei estruturas para um condomínio em relevo e a Serra-Ferro calculou o vento certinho, com galvanização reforçada. Acabamento impecável.' },
    ],
    faqs: [
      { question: 'O aço resiste à umidade e ao vento das áreas altas de Cajamar?', answer: 'Sim. Aplicamos galvanização e pintura eletrostática a pó, e dimensionamos as estruturas para as cargas de vento do relevo de Cajamar, evitando corrosão e deformações por décadas.' },
      { question: 'Vocês fazem estruturas e coberturas de galpão em Cajamar?', answer: 'Sim. Atendemos o polo logístico de Polvilho e Jordanésia com estruturas metálicas, coberturas com telha termoacústica e mezaninos calculados, com projeto e ART.' },
      { question: 'Atendem também os condomínios residenciais de Cajamar?', answer: 'Sim. Fazemos escadas, guarda-corpos, portões e pergolados para os condomínios de alto padrão de Cajamar, respeitando as regras de acesso e horário de obra.' },
      { question: 'Emitem ART para as estruturas de Cajamar?', answer: 'Sim, todas as estruturas que exigem cálculo de carga acompanham ART assinada por engenheiro habilitado no CREA.' },
      { question: 'Qual a garantia da serralheria em Cajamar?', answer: 'Garantia contratual sobre a estrutura, a solda e o tratamento anticorrosivo, com galvanização e pintura eletrostática que resistem à umidade e ao vento das áreas altas.' },
    ],
  },
  {
    slug: 'serralheria-em-itapevi-sp',
    city: 'Itapevi',
    keyword: 'Serralheria em Itapevi SP',
    metaTitle: 'Serralheria em Itapevi SP | Portões, Escadas e Estruturas | Serra Ferro',
    metaDescription: 'Serralheria em Itapevi SP para obras novas e condomínios: portões, escadas, mezaninos e estruturas metálicas sob medida, projetados desde a planta. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • SERRALHERIA EM ITAPEVI SP',
      description: 'Serralheria em Itapevi para obras novas e condomínios em crescimento: portões, escadas, mezaninos e estruturas metálicas projetados desde a planta, com solda fina e prazo em contrato.',
      highlights: ['Ideal para obra nova', 'Projeto de aço desde a planta', 'Portões, escadas e mezaninos', 'Prazo garantido em contrato'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM ITAPEVI',
      title: 'Serralheria em Itapevi para Obra Nova e Condomínios',
      paragraphs: [
        'Itapevi cresce com novos condomínios e casas em bairros como Cohab, Jardim Briquet e Vila Nova Itapevi. Entrar na fase de estrutura com o serralheiro certo evita retrabalho: projetamos escadas, mezaninos e chumbadores junto com a obra, garantindo encaixe perfeito e segurança.',
        'Fabricamos portões automáticos, grades de proteção, guarda-corpos e estruturas metálicas sob medida em Itapevi, com solda fina, pintura durável e cronograma definido em contrato.',
      ],
      bullets: ['Especialistas em obra nova', 'Chumbadores e estrutura na planta', 'Cobertura na Cohab e Jardim Briquet', 'Portões e grades de segurança'],
    },
    headers: {
      servicesTitle: 'Serralheria em Itapevi SP: Serviços Sob Medida',
      servicesSubtitle: 'Portões, escadas, mezaninos e estruturas metálicas sob medida para obras novas e condomínios de Itapevi, projetados desde a planta.',
      linesTitle: 'Linhas de Serralheria para Obras em Itapevi',
      linesSubtitle: 'Do custo-benefício estrutural à serralheria fina, escolha a linha ideal para a sua obra em Itapevi.',
      casesTitle: 'Projetos de Serralheria Entregues em Itapevi',
      casesSubtitle: 'Portões, escadas e estruturas executados em obras novas e condomínios de Itapevi.',
      testimonialsTitle: 'Quem Contratou Serralheria em Itapevi Recomenda',
      testimonialsSubtitle: 'Moradores e construtores de Itapevi comentam a pontualidade e o acabamento.',
      faqTitle: 'Dúvidas sobre Serralheria em Itapevi',
      faqSubtitle: 'Respostas para portões, escadas e estruturas em obras de Itapevi.',
      contactTitle: 'Peça um Orçamento de Serralheria em Itapevi SP',
      contactSubtitle: 'Agende a medição da sua obra em Itapevi e fale com o comercial técnico pelo WhatsApp.',
    },
    cases: [
      { title: 'Escada Estrutural - Casa Nova em Jardim Briquet (Itapevi)', region: 'Jardim Briquet - Itapevi', description: 'Escada metálica projetada desde a planta, com viga central e degraus em chapa dobrada, integrada à laje sem retrabalho.', image: IMG.serr, highlight: 'Projeto na Planta' },
      { title: 'Portão Automático - Cohab (Itapevi)', region: 'Cohab - Itapevi', description: 'Portão deslizante automático em chapa de aço com bom custo-benefício, motor rápido e pintura anticorrosiva.', image: IMG.house, highlight: 'Custo-Benefício' },
      { title: 'Mezanino Metálico - Vila Nova (Itapevi)', region: 'Vila Nova - Itapevi', description: 'Mezanino estrutural em aço para ampliar a área útil, calculado por engenharia e com guarda-corpo metálico.', image: IMG.min, highlight: 'Mezanino Calculado' },
    ],
    testimonials: [
      { author: 'Anderson Melo', role: 'Proprietário de casa nova em Itapevi', text: 'Chamei ainda na obra e a escada saiu perfeita, encaixada na laje. Montagem no prazo e acabamento acima do que eu esperava.' },
      { author: 'Eng. Priscila Santos', role: 'Construtora em Itapevi', text: 'Deixaram os chumbadores certos desde a estrutura e não tivemos retrabalho. Portões e grades entregues com documentação em ordem.' },
      { author: 'Arq. Bruno Camargo', role: 'Arquiteto em Itapevi', text: 'Projetei escadas e mezaninos para obras novas e a Serra-Ferro executou desde a estrutura, sem retrabalho. Solda fina e prazo cumprido.' },
    ],
    faqs: [
      { question: 'Vale chamar vocês na fase de obra em Itapevi?', answer: 'Sim. O ideal é definir escadas, mezaninos e chumbadores na fase de estrutura, para que tudo encaixe perfeitamente e sem retrabalho, com segurança garantida.' },
      { question: 'Vocês têm opções de bom custo-benefício em Itapevi?', answer: 'Sim. Oferecemos portões, grades e estruturas com excelente custo-benefício, sem abrir mão da solda fina e da pintura anticorrosiva da Serra-Ferro.' },
      { question: 'Fazem portões automáticos em Itapevi?', answer: 'Sim, fabricamos e instalamos portões deslizantes e basculantes automáticos, com motores de alta durabilidade e abertura rápida.' },
      { question: 'Emitem ART para mezaninos e estruturas em Itapevi?', answer: 'Sim, estruturas com cálculo de carga acompanham ART assinada por engenheiro no CREA.' },
      { question: 'Qual a garantia da serralheria em Itapevi?', answer: 'Garantia contratual sobre a solda, a pintura anticorrosiva e a estabilidade estrutural, com ART para mezaninos e estruturas que exigem cálculo.' },
    ],
  },
  {
    slug: 'serralheria-em-barueri-sp',
    city: 'Barueri',
    keyword: 'Serralheria em Barueri SP',
    metaTitle: 'Serralheria em Barueri SP | Escadas, Portões e Estruturas | Serra Ferro',
    metaDescription: 'Serralheria em Barueri SP com fábrica própria em Alphaville: escadas de design, portões, mezaninos e estruturas metálicas sob medida com solda invisível. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • SERRALHERIA EM BARUERI SP',
      description: 'Somos fábrica de serralheria em Barueri, sediada em Alphaville Industrial. Executamos escadas de design, portões, mezaninos e estruturas corporativas com solda invisível e agilidade de fábrica local.',
      highlights: ['Fábrica própria em Barueri', 'Residencial e corporativo', 'Solda invisível ao toque', 'Cálculo estrutural com ART'],
    },
    localIntro: {
      tag: 'FÁBRICA LOCAL EM BARUERI',
      title: 'Fábrica de Serralheria em Barueri e Alphaville',
      paragraphs: [
        'Com a fábrica na Alameda Rio Negro, em Alphaville Industrial, atendemos Barueri com agilidade máxima — de escadas e portões residenciais em Alphaville e Tamboré a mezaninos e estruturas metálicas de edifícios corporativos ao longo da Castello Branco.',
        'Cada peça recebe solda lixada e invisível, pintura eletrostática durável e, quando há carga, projeto executivo com ART. A proximidade garante medição rápida e suporte técnico presencial.',
      ],
      bullets: ['Sede na Al. Rio Negro, Alphaville', 'Escadas, portões e mezaninos', 'Estruturas corporativas de aço', 'Faturamento direto de fábrica'],
    },
    headers: {
      servicesTitle: 'Serralheria em Barueri SP: Serviços de Alto Padrão',
      servicesSubtitle: 'Da residência de condomínio à torre corporativa, executamos escadas, portões, mezaninos e estruturas metálicas em Barueri com a agilidade de fábrica local.',
      linesTitle: 'Linhas de Serralheria para Obras em Barueri',
      linesSubtitle: 'Da serralheria fina ao aço estrutural pesado, escolha a linha ideal para o padrão da sua obra em Barueri.',
      casesTitle: 'Projetos de Serralheria Entregues em Barueri e Alphaville',
      casesSubtitle: 'Escadas de design e estruturas metálicas executadas em condomínios e empreendimentos de Barueri.',
      testimonialsTitle: 'Quem Contratou Serralheria em Barueri Aprova',
      testimonialsSubtitle: 'Clientes e arquitetos de Barueri e Alphaville comentam o acabamento e a pontualidade.',
      faqTitle: 'Dúvidas sobre Serralheria em Barueri',
      faqSubtitle: 'Respostas para escadas, portões e estruturas em Barueri, Alphaville e Tamboré.',
      contactTitle: 'Peça um Orçamento de Serralheria em Barueri SP',
      contactSubtitle: 'Estamos na sua cidade, em Alphaville. Fale com o comercial técnico no WhatsApp e tire seu projeto de aço do papel.',
    },
    cases: [
      { title: 'Escada Plissada - Alphaville (Barueri)', region: 'Alphaville - Barueri', description: 'Escada plissada em chapa de aço dobrada com solda invisível e pintura epóxi fosca, peça central de residência de alto padrão.', image: IMG.serr, highlight: 'Escada Plissada' },
      { title: 'Estrutura Corporativa - Alphaville Industrial (Barueri)', region: 'Alphaville Industrial - Barueri', description: 'Mezanino e passarela metálica para sede corporativa, calculados por engenharia, com ART e guarda-corpo de aço e vidro.', image: IMG.min, highlight: 'Estrutura Corporativa' },
      { title: 'Portão Pivotante - Tamboré (Barueri)', region: 'Tamboré - Barueri', description: 'Portão de entrada pivotante em aço com revestimento corten e estrutura anti-empenamento para grande vão.', image: IMG.house, highlight: 'Portão Monumental' },
    ],
    testimonials: [
      { author: 'Ricardo Fontes', role: 'Proprietário em Alphaville, Barueri', text: 'Como a fábrica é aqui do lado, mediram e instalaram a escada rapidinho. Solda invisível e acabamento impecável.' },
      { author: 'Eng. Tatiana Lopes', role: 'Construtora em Barueri', text: 'Executaram a estrutura do mezanino corporativo com ART e pontualidade. Serralheria de fábrica local faz diferença no cronograma.' },
      { author: 'Arq. Fernanda Lima', role: 'Arquiteta em Barueri', text: 'A escada de design ficou perfeita, com solda invisível e ART. Ter a fábrica em Alphaville agilizou tudo, da medição à instalação.' },
    ],
    faqs: [
      { question: 'A fábrica de serralheria fica em Barueri?', answer: 'Sim, na Alameda Rio Negro, 229, Alphaville Industrial, Barueri. Isso garante medição, fabricação e instalação ágeis para qualquer obra na cidade.' },
      { question: 'Atendem residências e obras corporativas em Barueri?', answer: 'Sim. Fazemos escadas e portões residenciais em Alphaville e Tamboré e também mezaninos e estruturas metálicas para edifícios corporativos, com faturamento direto.' },
      { question: 'A solda fica invisível nas escadas?', answer: 'Sim. Lixamos e tratamos cada solda até ficar invisível ao toque, com pintura eletrostática curada em forno para durabilidade.' },
      { question: 'Emitem ART para estruturas em Barueri?', answer: 'Sim, mezaninos e estruturas com cálculo de carga acompanham ART registrada no CREA.' },
      { question: 'Qual a garantia da serralheria em Barueri?', answer: 'Garantia contratual sobre a execução, o tratamento anticorrosivo e a estabilidade estrutural, com laudos e ART e suporte técnico da fábrica local.' },
    ],
  },
  {
    slug: 'serralheria-em-cotia-sp',
    city: 'Cotia',
    keyword: 'Serralheria em Cotia SP',
    metaTitle: 'Serralheria em Cotia SP | Portões, Escadas e Estruturas | Serra Ferro',
    metaDescription: 'Serralheria em Cotia SP para casas de condomínio na Granja Viana: portões, escadas, pergolados e estruturas metálicas com tratamento anticorrosivo para a umidade da mata.',
    hero: {
      tag: 'SERRA-FERRO • SERRALHERIA EM COTIA SP',
      description: 'Serralheria em Cotia e Granja Viana para casas de condomínio cercadas de mata: portões, escadas, pergolados e estruturas metálicas com tratamento anticorrosivo reforçado contra a umidade.',
      highlights: ['Anticorrosão para clima úmido', 'Portões e estruturas de condomínio', 'Escadas e pergolados de design', 'Solda fina e pintura durável'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM COTIA',
      title: 'Serralheria em Cotia e Granja Viana para Casas de Condomínio',
      paragraphs: [
        'Os condomínios de Cotia e da Granja Viana, cercados por mata atlântica úmida, exigem serralheria com tratamento anticorrosivo severo. Fabricamos portões, escadas, pergolados e estruturas metálicas com galvanização e pintura eletrostática que resistem à umidade e à variação de temperatura da região.',
        'Do portão de entrada aos guarda-corpos e coberturas metálicas voltadas ao verde, executamos com solda fina, projeto e ART quando necessário, respeitando as regras de acesso dos condomínios.',
      ],
      bullets: ['Cobertura em Granja Viana e Caucaia do Alto', 'Galvanização contra umidade da mata', 'Pergolados e coberturas metálicas', 'Portões e guarda-corpos de condomínio'],
    },
    headers: {
      servicesTitle: 'Serralheria em Cotia SP: Serviços Sob Medida',
      servicesSubtitle: 'Portões, escadas, pergolados e estruturas metálicas sob medida para casas de condomínio em Cotia, com tratamento anticorrosivo para o clima úmido.',
      linesTitle: 'Linhas de Serralheria para Obras em Cotia',
      linesSubtitle: 'Do aço estrutural à serralheria fina, escolha a linha ideal para a sua casa em Cotia e Granja Viana.',
      casesTitle: 'Projetos de Serralheria Entregues em Cotia e Região',
      casesSubtitle: 'Portões, escadas e estruturas executados em condomínios de Cotia com durabilidade contra a umidade.',
      testimonialsTitle: 'Quem Contratou Serralheria em Cotia Recomenda',
      testimonialsSubtitle: 'Moradores de condomínios de Cotia e Granja Viana comentam a resistência à corrosão e o acabamento.',
      faqTitle: 'Dúvidas sobre Serralheria em Cotia',
      faqSubtitle: 'Respostas técnicas para portões, escadas e estruturas em Cotia e Granja Viana.',
      contactTitle: 'Peça um Orçamento de Serralheria em Cotia SP',
      contactSubtitle: 'Agende a visita técnica da sua casa em Cotia ou Granja Viana pelo WhatsApp.',
    },
    cases: [
      { title: 'Pergolado Metálico - Granja Viana (Cotia)', region: 'Granja Viana - Cotia', description: 'Pergolado em aço galvanizado com pintura fosca voltado ao jardim, tratado contra a umidade constante da mata.', image: IMG.min, highlight: 'Pergolado' },
      { title: 'Portão e Guarda-Corpo - San Fernando (Cotia)', region: 'San Fernando - Cotia', description: 'Portão de entrada e guarda-corpo metálico com galvanização reforçada e solda fina para residência arborizada.', image: IMG.house, highlight: 'Anticorrosão' },
      { title: 'Escada Metálica - Caucaia do Alto (Cotia)', region: 'Caucaia do Alto - Cotia', description: 'Escada metálica com degraus em chapa dobrada e guarda-corpo de aço, com acabamento durável para clima úmido.', image: IMG.serr, highlight: 'Escada Residencial' },
    ],
    testimonials: [
      { author: 'Fernanda Ribeiro', role: 'Moradora de condomínio na Granja Viana, Cotia', text: 'Nossa casa é cercada de mata e ferro sempre enferrujava. O portão e o pergolado da Serra-Ferro continuam intactos depois de dois anos.' },
      { author: 'Arq. Paulo Sérgio', role: 'Arquiteto em Cotia', text: 'Peças metálicas com acabamento fino e proteção anticorrosiva de verdade. Essencial para as casas que projeto em Cotia.' },
      { author: 'Eng. Rafael Moura', role: 'Construtora em Cotia', text: 'Portões e estruturas em condomínio de mata pedem proteção reforçada. A galvanização da Serra-Ferro segurou a umidade e o acabamento continua intacto.' },
    ],
    faqs: [
      { question: 'Como o aço resiste à umidade da mata em Cotia?', answer: 'Aplicamos galvanização e pintura eletrostática a pó, criando barreira dupla contra a corrosão típica dos terrenos arborizados e úmidos de Cotia e Granja Viana.' },
      { question: 'Vocês atendem condomínios fechados em Cotia?', answer: 'Sim, atendemos Granja Viana, San Fernando, Vale dos Sonhos e Caucaia do Alto, respeitando as regras de acesso e horário de obra.' },
      { question: 'Fazem pergolados e coberturas metálicas em Cotia?', answer: 'Sim, executamos pergolados, coberturas e estruturas metálicas voltadas ao paisagismo, com tratamento reforçado contra a umidade.' },
      { question: 'Emitem ART para estruturas em Cotia?', answer: 'Sim, estruturas com cálculo de carga acompanham ART assinada por engenheiro no CREA.' },
      { question: 'Qual a garantia da serralheria em Cotia?', answer: 'Garantia contratual sobre a solda, o tratamento anticorrosivo e a estrutura, com galvanização e pintura que enfrentam a umidade constante da mata de Cotia.' },
    ],
  },
  {
    slug: 'serralheria-em-embu-das-artes-sp',
    city: 'Embu das Artes',
    keyword: 'Serralheria em Embu das Artes SP',
    metaTitle: 'Serralheria em Embu das Artes SP | Peças de Design em Aço | Serra Ferro',
    metaDescription: 'Serralheria em Embu das Artes SP: portões, escadas, brises e peças autorais em aço e corten, unindo design e engenharia. Copy sob medida e acabamento fino. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • SERRALHERIA EM EMBU DAS ARTES SP',
      description: 'Serralheria de autor em Embu das Artes: portões, escadas, brises e painéis em aço e corten com forte apelo estético, unindo o design da cidade das artes à engenharia e ao acabamento fino.',
      highlights: ['Peças autorais de design', 'Aço corten e corte a laser', 'Casas de campo e ateliês', 'Solda invisível ao toque'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM EMBU DAS ARTES',
      title: 'Serralheria de Design em Embu das Artes',
      paragraphs: [
        'Cidade de forte vocação artística, Embu das Artes valoriza peças de aço com identidade: portões vazados cortados a laser, brises geométricos, escadas escultóricas e painéis em corten. Traduzimos essa estética em serralheria fina, com solda invisível e acabamento impecável.',
        'Atendemos casas de campo, ateliês e residências de charme em bairros como Jardim dos Manacás e Pinheirinho, unindo desenho autoral, corte CNC de precisão e proteção anticorrosiva para o clima úmido e ameno da região.',
      ],
      bullets: ['Portões vazados em corte a laser', 'Brises e painéis autorais', 'Aço corten com pátina natural', 'Cobertura em Jardim dos Manacás'],
    },
    headers: {
      servicesTitle: 'Serralheria em Embu das Artes SP: Peças de Design em Aço',
      servicesSubtitle: 'Portões, escadas, brises e painéis autorais em aço e corten para casas de campo e residências de charme em Embu das Artes.',
      linesTitle: 'Linhas de Serralheria para Obras em Embu das Artes',
      linesSubtitle: 'Da serralheria fina autoral ao aço corten, escolha a linha que combina com a estética da sua obra em Embu das Artes.',
      casesTitle: 'Projetos de Serralheria Entregues em Embu das Artes',
      casesSubtitle: 'Peças metálicas de design executadas em casas e ateliês de Embu das Artes com acabamento artesanal.',
      testimonialsTitle: 'Quem Contratou Serralheria em Embu das Artes Recomenda',
      testimonialsSubtitle: 'Moradores e artistas de Embu das Artes comentam o design e o acabamento das peças.',
      faqTitle: 'Dúvidas sobre Serralheria em Embu das Artes',
      faqSubtitle: 'Respostas técnicas para portões, brises e escadas de design em Embu das Artes.',
      contactTitle: 'Peça um Orçamento de Serralheria em Embu das Artes SP',
      contactSubtitle: 'Agende a visita técnica da sua casa em Embu das Artes e traga seu projeto autoral em aço pelo WhatsApp.',
    },
    cases: [
      { title: 'Portão Vazado a Laser - Jardim dos Manacás (Embu das Artes)', region: 'Jardim dos Manacás - Embu das Artes', description: 'Portão com desenho autoral cortado a laser CNC em chapa de aço, com pintura eletrostática e trilho reforçado.', image: IMG.house, highlight: 'Corte a Laser' },
      { title: 'Brises em Corten - Centro Histórico (Embu das Artes)', region: 'Centro Histórico - Embu das Artes', description: 'Painéis brises em aço corten com pátina natural controlada, sombreamento e privacidade para fachada de ateliê.', image: IMG.facade, highlight: 'Aço Corten' },
      { title: 'Escada Escultórica - Pinheirinho (Embu das Artes)', region: 'Pinheirinho - Embu das Artes', description: 'Escada metálica de desenho autoral com solda invisível e degraus em chapa dobrada, peça central da casa.', image: IMG.serr, highlight: 'Escada de Design' },
    ],
    testimonials: [
      { author: 'Rogério Bianchi', role: 'Artista plástico em Embu das Artes', text: 'Queria um portão que fosse quase uma escultura. Cortaram meu desenho a laser com uma precisão impressionante e acabamento perfeito.' },
      { author: 'Luciana Amaral', role: 'Moradora do Jardim dos Manacás, Embu das Artes', text: 'Os brises de corten deram outra cara para a fachada. Além de lindos, resolveram a privacidade e o sombreamento.' },
      { author: 'Arq. Tatiana Reis', role: 'Arquiteta em Embu das Artes', text: 'Pedi peças autorais em corten e a Serra-Ferro cortou meu desenho a laser com precisão impressionante. Design e engenharia juntos.' },
    ],
    faqs: [
      { question: 'Vocês cortam desenhos personalizados a laser em Embu das Artes?', answer: 'Sim. Fazemos corte a laser CNC de alta precisão para portões, painéis e brises com desenhos autorais, ideais para o perfil artístico de Embu das Artes.' },
      { question: 'O aço corten precisa de manutenção?', answer: 'Não. O corten desenvolve uma pátina natural protetora que dispensa pintura e manutenção periódica, com visual rústico e contemporâneo muito procurado na cidade.' },
      { question: 'A solda das escadas de design fica aparente?', answer: 'Não. Lixamos e tratamos cada solda até ficar invisível ao toque, preservando o desenho limpo das peças autorais.' },
      { question: 'Atendem casas de campo e ateliês em Embu das Artes?', answer: 'Sim, atendemos casas, ateliês e condomínios da cidade com medição no local e instalação por equipe própria.' },
      { question: 'Qual a garantia da serralheria em Embu das Artes?', answer: 'Garantia contratual sobre a execução e o acabamento das peças, incluindo tratamento anticorrosivo, com aço corten que dispensa manutenção e pintura curada em forno.' },
    ],
  },
  {
    slug: 'serralheria-em-taboao-da-serra-sp',
    city: 'Taboão da Serra',
    keyword: 'Serralheria em Taboão da Serra SP',
    metaTitle: 'Serralheria em Taboão da Serra SP | Portões, Grades e Escadas | Serra Ferro',
    metaDescription: 'Serralheria em Taboão da Serra SP para casas e reformas: portões automáticos, grades de segurança, escadas e estruturas metálicas sob medida com acabamento fino. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • SERRALHERIA EM TABOÃO DA SERRA SP',
      description: 'Serralheria em Taboão da Serra para casas, sobrados e reformas: portões automáticos, grades de segurança, escadas e estruturas metálicas sob medida, com solda fina e pintura durável.',
      highlights: ['Portões e grades de segurança', 'Ideal para reforma e retrofit', 'Escadas e estruturas metálicas', 'Instalação limpa e rápida'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM TABOÃO DA SERRA',
      title: 'Serralheria em Taboão da Serra para Casas e Reformas',
      paragraphs: [
        'Na divisa com a capital, Taboão da Serra é densa e movimentada, e a segurança é prioridade. Fabricamos portões automáticos reforçados, grades de proteção e guarda-corpos com desenho moderno, unindo robustez e estética para sobrados e comércios.',
        'Somos especialistas em reforma: medimos vãos existentes, substituímos portões e grades antigos e reforçamos escadas, com instalação limpa que preserva o acabamento pronto.',
      ],
      bullets: ['Portões automáticos reforçados', 'Grades e guarda-corpos de segurança', 'Especialistas em reforma', 'Atendimento no Pirajuçara e centro'],
    },
    headers: {
      servicesTitle: 'Serralheria em Taboão da Serra SP: Serviços Sob Medida',
      servicesSubtitle: 'Portões automáticos, grades, escadas e estruturas metálicas sob medida para casas e reformas em Taboão da Serra, com segurança e acabamento fino.',
      linesTitle: 'Linhas de Serralheria para Obras em Taboão da Serra',
      linesSubtitle: 'Do custo-benefício estrutural à serralheria fina, escolha a melhor opção para o seu imóvel em Taboão da Serra.',
      casesTitle: 'Projetos de Serralheria Entregues em Taboão da Serra',
      casesSubtitle: 'Portões, grades e escadas executados em casas e sobrados de Taboão da Serra.',
      testimonialsTitle: 'Quem Contratou Serralheria em Taboão da Serra Aprova',
      testimonialsSubtitle: 'Moradores de Taboão da Serra comentam a segurança e o acabamento das peças.',
      faqTitle: 'Dúvidas sobre Serralheria em Taboão da Serra',
      faqSubtitle: 'Respostas para portões, grades e escadas em Taboão da Serra.',
      contactTitle: 'Peça um Orçamento de Serralheria em Taboão da Serra SP',
      contactSubtitle: 'Agende a medição do seu imóvel em Taboão da Serra e fale com o comercial pelo WhatsApp.',
    },
    cases: [
      { title: 'Portão Automático - Jardim Henriqueta (Taboão da Serra)', region: 'Jardim Henriqueta - Taboão da Serra', description: 'Portão deslizante automático reforçado em chapa de aço, com motor rápido e pintura anticorrosiva, para sobrado em rua movimentada.', image: IMG.house, highlight: 'Segurança' },
      { title: 'Grades de Proteção - Pirajuçara (Taboão da Serra)', region: 'Pirajuçara - Taboão da Serra', description: 'Grades de janela e portãozinho com desenho moderno e solda fina, unindo proteção e estética.', image: IMG.min, highlight: 'Grades Modernas' },
      { title: 'Escada Metálica - Parque Assunção (Taboão da Serra)', region: 'Parque Assunção - Taboão da Serra', description: 'Escada metálica compacta com guarda-corpo de aço para sobrado, otimizando espaço com segurança.', image: IMG.serr, highlight: 'Escada Compacta' },
    ],
    testimonials: [
      { author: 'Sandra Prado', role: 'Moradora do Jardim Henriqueta, Taboão da Serra', text: 'Troquei o portão antigo por um automático reforçado. Muito mais seguro, silencioso e com acabamento que valorizou a fachada.' },
      { author: 'Wagner Lima', role: 'Proprietário de sobrado em Taboão da Serra', text: 'Fizeram as grades e a escada sem sujeira e no prazo. Serralheria fina com preço justo, difícil de achar na região.' },
      { author: 'Eng. Marcos Vieira', role: 'Reformas em Taboão da Serra', text: 'Portões automáticos e grades reforçadas para segurança. A Serra-Ferro entregou com solda fina e instalação limpa, sem quebrar nada.' },
    ],
    faqs: [
      { question: 'Vocês fazem portões automáticos em Taboão da Serra?', answer: 'Sim. Fabricamos e instalamos portões deslizantes e basculantes automáticos reforçados, com motores de alta durabilidade, ideais para a segurança das ruas movimentadas de Taboão da Serra.' },
      { question: 'Fazem só a troca de portões e grades antigos?', answer: 'Sim. Somos especialistas em reforma: medimos, fabricamos sob medida e substituímos portões, grades e escadas com instalação limpa, sem danificar o acabamento.' },
      { question: 'As grades podem ter desenho moderno?', answer: 'Sim, fazemos grades e guarda-corpos com desenho contemporâneo e solda fina, unindo segurança e estética.' },
      { question: 'Atendem sobrados e comércios em Taboão da Serra?', answer: 'Sim, atendemos casas, sobrados e comércios da cidade, do Pirajuçara ao centro.' },
      { question: 'Qual a garantia da serralheria em Taboão da Serra?', answer: 'Garantia contratual sobre a estrutura, os motores dos portões e o tratamento anticorrosivo, com componentes de alta durabilidade.' },
    ],
  },
  {
    slug: 'serralheria-em-osasco-sp',
    city: 'Osasco',
    keyword: 'Serralheria em Osasco SP',
    metaTitle: 'Serralheria em Osasco SP | Estruturas, Escadas e Guarda-Corpos | Serra Ferro',
    metaDescription: 'Serralheria em Osasco SP para prédios e casas: estruturas metálicas, escadas de emergência, guarda-corpos e portões sob medida com ART e acabamento fino. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • SERRALHERIA EM OSASCO SP',
      description: 'Serralheria em Osasco para edifícios e residências: estruturas metálicas, escadas de emergência, guarda-corpos e portões sob medida, com cálculo estrutural, ART e acabamento fino.',
      highlights: ['Estruturas e escadas prediais', 'Guarda-corpos e portões', 'Cálculo com ART', 'Retrofit e obra nova'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM OSASCO',
      title: 'Serralheria em Osasco para Edifícios e Residências',
      paragraphs: [
        'Uma das cidades mais verticalizadas da Grande São Paulo, Osasco demanda serralheria predial: escadas de emergência, guarda-corpos metálicos, estruturas e passarelas, além de portões e grades residenciais em bairros como Bela Vista, Vila Yara e Km 18.',
        'Executamos com cálculo de carga, ART e solda fina, atendendo tanto retrofit de edifícios quanto obras novas, com logística que respeita a rotina do condomínio.',
      ],
      bullets: ['Escadas de emergência e passarelas', 'Guarda-corpos metálicos com norma', 'Retrofit de estruturas prediais', 'Cobertura na Bela Vista e Km 18'],
    },
    headers: {
      servicesTitle: 'Serralheria em Osasco SP: Estruturas e Serralheria Fina',
      servicesSubtitle: 'Estruturas metálicas, escadas, guarda-corpos e portões sob medida para edifícios e residências de Osasco, com cálculo e ART.',
      linesTitle: 'Linhas de Serralheria para Obras em Osasco',
      linesSubtitle: 'Do aço estrutural pesado à serralheria fina, escolha a linha ideal para a sua obra predial ou residencial em Osasco.',
      casesTitle: 'Projetos de Serralheria Entregues em Osasco',
      casesSubtitle: 'Estruturas, escadas e guarda-corpos executados em edifícios e casas de Osasco.',
      testimonialsTitle: 'Quem Contratou Serralheria em Osasco Aprova',
      testimonialsSubtitle: 'Síndicos e moradores de Osasco comentam a robustez e a documentação técnica.',
      faqTitle: 'Dúvidas sobre Serralheria em Osasco',
      faqSubtitle: 'Respostas para estruturas, escadas e guarda-corpos em Osasco.',
      contactTitle: 'Peça um Orçamento de Serralheria em Osasco SP',
      contactSubtitle: 'Agende a visita técnica do seu edifício ou casa em Osasco pelo WhatsApp.',
    },
    cases: [
      { title: 'Escada de Emergência - Edifício no Centro (Osasco)', region: 'Centro - Osasco', description: 'Escada de emergência metálica externa calculada por engenharia, com guarda-corpo normatizado e ART.', image: IMG.serr, highlight: 'Escada de Emergência' },
      { title: 'Guarda-Corpo Metálico - Bela Vista (Osasco)', region: 'Bela Vista - Osasco', description: 'Guarda-corpos de aço e vidro para varandas de torre, em conformidade com a NBR 14718, com fixação segura em altura.', image: IMG.vidro, highlight: 'Norma NBR 14718' },
      { title: 'Portão e Grades - Vila Yara (Osasco)', region: 'Vila Yara - Osasco', description: 'Portão automático e grades de proteção para residência, com solda fina e pintura anticorrosiva.', image: IMG.house, highlight: 'Residencial' },
    ],
    testimonials: [
      { author: 'Eng. Roberto Dias', role: 'Síndico de edifício no Centro de Osasco', text: 'Executaram a escada de emergência e os guarda-corpos do prédio com ART e dentro da norma. Organização e segurança impecáveis.' },
      { author: 'Patrícia Gomes', role: 'Moradora da Bela Vista, Osasco', text: 'O guarda-corpo da minha varanda ficou seguro e elegante. Instalação em andar alto feita com todo cuidado.' },
      { author: 'Eng. Vera Prado', role: 'Construtora em Osasco', text: 'Estruturas metálicas prediais entregues com ART e conformidade normativa. A Serra-Ferro respeitou o cronograma e a rotina do condomínio.' },
    ],
    faqs: [
      { question: 'Vocês fazem estruturas e escadas de emergência para prédios em Osasco?', answer: 'Sim. Executamos escadas de emergência, passarelas e estruturas metálicas prediais calculadas por engenharia, com ART e conformidade normativa.' },
      { question: 'Os guarda-corpos atendem à NBR 14718?', answer: 'Sim. Dimensionamos os guarda-corpos metálicos e de aço e vidro para os esforços da norma NBR 14718, essenciais em varandas de torres de Osasco.' },
      { question: 'Fazem retrofit de estruturas em edifícios de Osasco?', answer: 'Sim, atuamos em retrofit e reforço de estruturas, escadas e guarda-corpos prediais, com logística que respeita o condomínio.' },
      { question: 'Atendem também casas em Osasco?', answer: 'Sim, fazemos portões, grades e escadas residenciais em bairros como Vila Yara e Km 18.' },
      { question: 'Qual a garantia da serralheria em Osasco?', answer: 'Garantia contratual sobre a estrutura, a solda e o tratamento anticorrosivo, com ART e conformidade normativa para estruturas e guarda-corpos prediais.' },
    ],
  },
  {
    slug: 'serralheria-em-jandira-sp',
    city: 'Jandira',
    keyword: 'Serralheria em Jandira SP',
    metaTitle: 'Serralheria em Jandira SP | Portões, Grades e Escadas | Serra Ferro',
    metaDescription: 'Serralheria em Jandira SP para casas, sobrados e reformas: portões automáticos, grades, escadas e estruturas metálicas com ótimo custo-benefício e acabamento fino. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • SERRALHERIA EM JANDIRA SP',
      description: 'Serralheria em Jandira para casas, sobrados e reformas: portões automáticos, grades, escadas e estruturas metálicas sob medida, com excelente custo-benefício e acabamento fino.',
      highlights: ['Ótimo custo-benefício', 'Portões e grades sob medida', 'Ideal para reforma e obra nova', 'Solda fina e pintura durável'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM JANDIRA',
      title: 'Serralheria em Jandira com Custo-Benefício e Acabamento Fino',
      paragraphs: [
        'Cidade compacta do oeste da Grande São Paulo, Jandira reúne casas e sobrados em bairros como Jardim Sabará e Vila Eutália. Entregamos portões automáticos, grades, escadas e estruturas metálicas com excelente custo-benefício, sem abrir mão da solda fina e da pintura anticorrosiva.',
        'Somos especialistas em reforma e substituição de peças antigas, com medição precisa e instalação limpa, do portão de entrada às grades de segurança.',
      ],
      bullets: ['Excelente custo-benefício', 'Portões automáticos e grades', 'Especialistas em reforma', 'Cobertura no Jardim Sabará e Vila Eutália'],
    },
    headers: {
      servicesTitle: 'Serralheria em Jandira SP: Serviços Sob Medida',
      servicesSubtitle: 'Portões, grades, escadas e estruturas metálicas sob medida para casas, sobrados e reformas em Jandira, com ótimo custo-benefício.',
      linesTitle: 'Linhas de Serralheria para Obras em Jandira',
      linesSubtitle: 'Do custo-benefício estrutural à serralheria fina, escolha a melhor opção para o seu imóvel em Jandira.',
      casesTitle: 'Projetos de Serralheria Entregues em Jandira',
      casesSubtitle: 'Portões, grades e escadas executados em casas e sobrados de Jandira com bom custo-benefício.',
      testimonialsTitle: 'Quem Contratou Serralheria em Jandira Aprova',
      testimonialsSubtitle: 'Moradores de Jandira comentam o custo-benefício e o acabamento das peças.',
      faqTitle: 'Dúvidas sobre Serralheria em Jandira',
      faqSubtitle: 'Respostas para portões, grades e escadas em Jandira.',
      contactTitle: 'Peça um Orçamento de Serralheria em Jandira SP',
      contactSubtitle: 'Agende a medição da sua casa ou sobrado em Jandira pelo WhatsApp.',
    },
    cases: [
      { title: 'Portão Automático - Jardim Sabará (Jandira)', region: 'Jardim Sabará - Jandira', description: 'Portão deslizante automático em chapa de aço com bom custo-benefício, motor rápido e pintura anticorrosiva.', image: IMG.house, highlight: 'Custo-Benefício' },
      { title: 'Grades e Guarda-Corpo - Vila Eutália (Jandira)', region: 'Vila Eutália - Jandira', description: 'Grades de segurança e guarda-corpo com desenho moderno e solda fina para sobrado.', image: IMG.min, highlight: 'Segurança' },
      { title: 'Escada Metálica - Centro (Jandira)', region: 'Centro - Jandira', description: 'Escada metálica compacta com guarda-corpo de aço, otimizando espaço com acabamento fino.', image: IMG.serr, highlight: 'Escada Compacta' },
    ],
    testimonials: [
      { author: 'Juliana Freitas', role: 'Moradora do Jardim Sabará, Jandira', text: 'Portão automático novo com um preço muito justo e acabamento ótimo. Instalação rápida e sem bagunça.' },
      { author: 'Marcos Aurélio', role: 'Proprietário de sobrado em Jandira', text: 'Fizeram grades e a escada com solda fina, coisa que eu não esperava pelo valor. Recomendo demais.' },
      { author: 'Eng. Paulo Renato', role: 'Construtora em Jandira', text: 'Custo-benefício com acabamento fino. Portões, grades e escadas entregues com solda fina e pintura anticorrosiva, no prazo combinado.' },
    ],
    faqs: [
      { question: 'A serralheria da Serra-Ferro tem bom custo-benefício para Jandira?', answer: 'Sim. Entregamos portões, grades e escadas com excelente custo-benefício, mantendo a solda fina e a pintura anticorrosiva que são marca da Serra-Ferro.' },
      { question: 'Vocês fazem a troca de portões e grades antigos em Jandira?', answer: 'Sim, somos especialistas em reforma: medimos, fabricamos sob medida e substituímos com instalação limpa, sem danificar o acabamento.' },
      { question: 'Fazem portões automáticos em Jandira?', answer: 'Sim, instalamos portões deslizantes e basculantes automáticos com motores de alta durabilidade e abertura rápida.' },
      { question: 'Atendem casas e sobrados em Jandira?', answer: 'Sim, atendemos toda a cidade, do Jardim Sabará à Vila Eutália e centro.' },
      { question: 'Qual a garantia da serralheria em Jandira?', answer: 'Garantia contratual sobre a solda, a pintura anticorrosiva e a estrutura das peças, mesmo nas opções de melhor custo-benefício.' },
    ],
  },
  {
    slug: 'serralheria-em-santana-de-parnaiba-sp',
    city: 'Santana de Parnaíba',
    keyword: 'Serralheria em Santana de Parnaíba SP',
    metaTitle: 'Serralheria em Santana de Parnaíba SP | Escadas, Portões e Estruturas | Serra Ferro',
    metaDescription: 'Serralheria em Santana de Parnaíba SP para os condomínios de Alphaville e casarões: escadas, portões monumentais, coberturas e estruturas metálicas calculadas para vento. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • SERRALHERIA EM SANTANA DE PARNAÍBA SP',
      description: 'Serralheria em Santana de Parnaíba para condomínios de Alphaville e casarões: escadas de design, portões monumentais, coberturas e estruturas metálicas calculadas para o vento das áreas altas.',
      highlights: ['Cálculo estrutural para vento', 'Portões e escadas monumentais', 'Condomínios de Alphaville Residencial', 'Solda invisível ao toque'],
    },
    localIntro: {
      tag: 'ATENDIMENTO LOCAL EM SANTANA DE PARNAÍBA',
      title: 'Serralheria em Santana de Parnaíba e Alphaville Residencial',
      paragraphs: [
        'Santana de Parnaíba abriga residenciais de Alphaville e condomínios de luxo em áreas elevadas, onde coberturas, pergolados e portões precisam ser dimensionados para o vento. Executamos escadas de design, portões monumentais e estruturas metálicas com engenharia e acabamento de alto padrão.',
        'Do centro histórico aos condomínios contemporâneos, entregamos serralheria fina com solda invisível, tratamento anticorrosivo e ART quando há cálculo de carga.',
      ],
      bullets: ['Residenciais Alphaville e Tamboré', 'Coberturas e pergolados para vento', 'Escadas e portões monumentais', 'Solda fina e ART'],
    },
    headers: {
      servicesTitle: 'Serralheria em Santana de Parnaíba SP: Alto Padrão',
      servicesSubtitle: 'Escadas de design, portões monumentais, coberturas e estruturas metálicas sob medida para casarões e condomínios de Santana de Parnaíba, calculados para vento.',
      linesTitle: 'Linhas de Serralheria para Obras em Santana de Parnaíba',
      linesSubtitle: 'Da serralheria fina ao aço estrutural, escolha a linha certa para grandes vãos e áreas expostas ao vento.',
      casesTitle: 'Projetos de Serralheria Entregues em Santana de Parnaíba',
      casesSubtitle: 'Escadas, portões e estruturas executados nos condomínios de Alphaville Residencial e região.',
      testimonialsTitle: 'Quem Contratou Serralheria em Santana de Parnaíba Recomenda',
      testimonialsSubtitle: 'Moradores dos condomínios de Santana de Parnaíba comentam a robustez e o acabamento.',
      faqTitle: 'Dúvidas sobre Serralheria em Santana de Parnaíba',
      faqSubtitle: 'Respostas técnicas para escadas, portões e estruturas em Alphaville Residencial e região.',
      contactTitle: 'Peça um Orçamento de Serralheria em Santana de Parnaíba SP',
      contactSubtitle: 'Agende a visita técnica do seu casarão ou residência em Santana de Parnaíba pelo WhatsApp.',
    },
    cases: [
      { title: 'Cobertura Metálica - Alphaville (Santana de Parnaíba)', region: 'Alphaville - Santana de Parnaíba', description: 'Cobertura metálica de grande vão para área de lazer, dimensionada para as cargas de vento das áreas altas do condomínio.', image: IMG.min, highlight: 'Reforço de Vento' },
      { title: 'Escada de Design - Tamboré (Santana de Parnaíba)', region: 'Tamboré - Santana de Parnaíba', description: 'Escada metálica escultórica com solda invisível e guarda-corpo de aço e vidro, integrando os pavimentos.', image: IMG.serr, highlight: 'Escada de Design' },
      { title: 'Portão Monumental - Centro Histórico (Santana de Parnaíba)', region: 'Centro Histórico - Santana de Parnaíba', description: 'Portão de entrada em aço com desenho compatível à fachada preservada, unindo estética e segurança.', image: IMG.house, highlight: 'Portão Monumental' },
    ],
    testimonials: [
      { author: 'Marcelo Tavares', role: 'Morador de Alphaville, Santana de Parnaíba', text: 'A cobertura metálica aguentou tempestades fortes sem qualquer problema. Dimensionaram tudo para o vento da região.' },
      { author: 'Arq. Beatriz Nunes', role: 'Arquiteta em Santana de Parnaíba', text: 'A escada escultórica ficou perfeita, com solda invisível e ART. Serralheria fina de verdade.' },
      { author: 'Eng. Henrique Salgado', role: 'Construtora em Santana de Parnaíba', text: 'Coberturas e estruturas dimensionadas para o vento das áreas altas, com ART. Escadas de design com solda invisível e acabamento de alto padrão.' },
    ],
    faqs: [
      { question: 'As coberturas e estruturas aguentam o vento das áreas altas de Santana de Parnaíba?', answer: 'Sim. Calculamos as cargas de vento de cada estrutura e reforçamos o dimensionamento, com ART, para coberturas, pergolados e portões nas áreas elevadas dos condomínios.' },
      { question: 'Vocês atendem os residenciais de Alphaville em Santana de Parnaíba?', answer: 'Sim, atendemos Alphaville, Tamboré e demais condomínios da cidade, respeitando as regras de acesso e horário de obra.' },
      { question: 'É possível fazer um portão compatível com fachada do centro histórico?', answer: 'Sim, desenhamos portões e grades que respeitam a estética preservada das fachadas históricas, unindo o visual original à segurança moderna.' },
      { question: 'A solda das escadas fica invisível?', answer: 'Sim, lixamos e tratamos cada solda até ficar invisível ao toque, com pintura eletrostática durável.' },
      { question: 'Qual a garantia da serralheria em Santana de Parnaíba?', answer: 'Garantia contratual sobre a estrutura, a solda e o tratamento anticorrosivo, com cálculo de vento e ART para coberturas, pergolados e portões das áreas elevadas.' },
    ],
  },
  {
    slug: 'serralheria-em-curitiba',
    city: 'Curitiba',
    keyword: 'Serralheria em Curitiba',
    metaTitle: 'Serralheria em Curitiba | Escadas, Portões e Estruturas | Serra Ferro',
    metaDescription: 'Serralheria em Curitiba: escadas de design, portões, mezaninos e estruturas metálicas sob medida com solda invisível e tratamento anticorrosivo para o clima úmido. Orçamento no WhatsApp.',
    hero: {
      tag: 'SERRA-FERRO • SERRALHERIA EM CURITIBA',
      description: 'Serralheria fina em Curitiba: escadas de design, portões, mezaninos e estruturas metálicas sob medida com solda invisível e tratamento anticorrosivo reforçado para a umidade e o frio da região.',
      highlights: ['Solda invisível ao toque', 'Anticorrosão para clima úmido', 'Escadas e portões de design', 'Cálculo estrutural com ART'],
    },
    localIntro: {
      tag: 'ATENDIMENTO EM CURITIBA',
      title: 'Serralheria Fina em Curitiba para Alto Padrão',
      paragraphs: [
        'A arquitetura sofisticada de Curitiba pede serralheria de autor — escadas escultóricas, portões marcantes, mezaninos e brises — mas o clima frio e úmido exige um tratamento anticorrosivo à altura. Executamos cada peça com solda lixada e invisível ao toque e proteção por galvanização e pintura eletrostática que resiste à umidade e às geadas.',
        'Atendemos residências e empreendimentos em bairros como Batel, Ecoville, Cabral e Água Verde, com detalhamento em CAD e emissão de ART quando há cálculo de carga, unindo design e engenharia.',
      ],
      bullets: ['Escadas helicoidais e plissadas', 'Galvanização contra umidade e frio', 'Portões e brises de design', 'Projeto executivo com ART'],
    },
    headers: {
      servicesTitle: 'Serralheria em Curitiba: Serviços de Alto Padrão',
      servicesSubtitle: 'Escadas de design, portões, mezaninos e estruturas metálicas sob medida para Curitiba, com solda invisível e tratamento anticorrosivo para o clima úmido.',
      linesTitle: 'Linhas de Serralheria para Obras em Curitiba',
      linesSubtitle: 'Da serralheria fina ao aço estrutural, escolha a linha ideal para o design e a carga da sua obra em Curitiba.',
      casesTitle: 'Projetos de Serralheria Entregues em Curitiba',
      casesSubtitle: 'Escadas de design e estruturas metálicas executadas em Curitiba com acabamento artesanal e proteção anticorrosiva.',
      testimonialsTitle: 'Quem Contratou Serralheria em Curitiba Recomenda',
      testimonialsSubtitle: 'Moradores e arquitetos de Curitiba comentam o acabamento e a durabilidade das peças.',
      faqTitle: 'Dúvidas sobre Serralheria em Curitiba',
      faqSubtitle: 'Respostas técnicas para escadas, portões e estruturas metálicas em Curitiba.',
      contactTitle: 'Peça um Orçamento de Serralheria em Curitiba',
      contactSubtitle: 'Agende a visita técnica da sua obra em Curitiba e tire seu projeto de aço do papel pelo WhatsApp.',
    },
    cases: [
      { title: 'Escada Helicoidal - Batel (Curitiba)', region: 'Batel - Curitiba', description: 'Escada helicoidal metálica com solda invisível e degraus em chapa dobrada, com pintura epóxi de alta durabilidade contra a umidade.', image: IMG.serr, highlight: 'Escada Helicoidal' },
      { title: 'Portão de Design - Ecoville (Curitiba)', region: 'Ecoville - Curitiba', description: 'Portão pivotante em aço com revestimento corten e galvanização reforçada, deslizamento leve e estrutura anti-empenamento.', image: IMG.house, highlight: 'Portão de Design' },
      { title: 'Mezanino Estrutural - Água Verde (Curitiba)', region: 'Água Verde - Curitiba', description: 'Mezanino com vigas metálicas aparentes e guarda-corpo de aço e vidro, calculado por engenharia e com ART.', image: IMG.min, highlight: 'Mezanino Calculado' },
    ],
    testimonials: [
      { author: 'Rafael Munhoz', role: 'Morador do Batel, Curitiba', text: 'A escada virou o ponto alto da casa. Solda invisível de verdade e o acabamento continua intacto apesar da umidade de Curitiba.' },
      { author: 'Arq. Camila Stroparo', role: 'Arquiteta em Curitiba', text: 'Detalharam a serralheria em CAD e entregaram a ART do mezanino. Peças de design com engenharia e proteção anticorrosiva impecável.' },
      { author: 'Eng. Gustavo Lima', role: 'Construtora em Curitiba', text: 'No clima úmido de Curitiba, a proteção anticorrosiva faz diferença. A Serra-Ferro entregou estruturas com galvanização e solda invisível, com ART.' },
    ],
    faqs: [
      { question: 'As peças de aço resistem à umidade e às geadas de Curitiba?', answer: 'Sim. Aplicamos galvanização e pintura eletrostática a pó curada em forno, criando barreira dupla contra a corrosão típica do clima frio e úmido de Curitiba.' },
      { question: 'A solda das escadas fica invisível?', answer: 'Sim, lixamos e tratamos cada solda até ficar invisível ao toque, preservando o desenho limpo das peças de design.' },
      { question: 'Vocês emitem ART para mezaninos e estruturas em Curitiba?', answer: 'Sim, estruturas com cálculo de carga acompanham ART assinada por engenheiro habilitado no CREA.' },
      { question: 'Atendem os bairros de alto padrão de Curitiba?', answer: 'Sim, atendemos Batel, Ecoville, Cabral, Água Verde e demais regiões da cidade, com medição no local.' },
      { question: 'Qual a garantia da serralheria em Curitiba?', answer: 'Garantia contratual sobre a solda, o tratamento anticorrosivo e a estrutura, com galvanização e pintura curada em forno que resistem à umidade e às geadas de Curitiba.' },
    ],
  },
];

export const SERRALHERIA_REGION_BY_SLUG: Record<string, RegionPage> = Object.fromEntries(
  SERRALHERIA_REGIONS.map((r) => [r.slug, r]),
);
